export default {
  ACTION_USERINFO_UPDATE: "ACTION_USERINFO_UPDATE",
  ACTION_GAMES_UPDATE: "ACTION_GAMES_UPDATE",
  ACTION_USERSETTING_UPDATE: "ACTION_USERSETTING_UPDATE",
  ACTION_ANNOUNCEMENT_UPDATE: "ACTION_ANNOUNCEMENT_UPDATE",
  ACTION_ANNOUNCEMENT_CLEAR: "ACTION_ANNOUNCEMENT_CLEAR"
};
