//IM 聯賽id(LeagueId) 對應 SCCompId
export const IMLeagueIdSCComp = {
	IMLeagueId_102:{SCCompId:524,SCCompName:"Serie A",IMCompName:"*Italy Serie A"},
	IMLeagueId_108:{SCCompId:669,SCCompName:"Eliteserien",IMCompName:"Norway Eliteserien"},
	IMLeagueId_114:{SCCompId:705,SCCompName:"Segunda Liga",IMCompName:"Portugal Liga Pro"},
	IMLeagueId_115:{SCCompId:400,SCCompName:"Veikkausliiga",IMCompName:"Finland Veikkausliiga"},
	IMLeagueId_118:{SCCompId:808,SCCompName:"Allsvenskan",IMCompName:"Sweden Allsvenskan"},
	IMLeagueId_119:{SCCompId:818,SCCompName:"Superettan",IMCompName:"Sweden Superettan"},
	IMLeagueId_120:{SCCompId:852,SCCompName:"Süper Lig",IMCompName:"Turkey Super League"},
	IMLeagueId_124:{SCCompId:823,SCCompName:"Challenge League",IMCompName:"Switzerland Challenge League"},
	IMLeagueId_126:{SCCompId:423,SCCompName:"2. Bundesliga",IMCompName:"Germany Bundesliga 2"},
	IMLeagueId_127:{SCCompId:527,SCCompName:"Serie B",IMCompName:"Italy Serie B"},
	IMLeagueId_130:{SCCompId:795,SCCompName:"LaLiga",IMCompName:"*Spain La Liga"},
	IMLeagueId_131:{SCCompId:413,SCCompName:"Ligue 2",IMCompName:"France Ligue 2"},
	IMLeagueId_132:{SCCompId:346,SCCompName:"Championship",IMCompName:"England League Championship"},
	IMLeagueId_134:{SCCompId:707,SCCompName:"Primeira Liga",IMCompName:"Portugal Super Liga"},
	IMLeagueId_191:{SCCompId:364,SCCompName:"Premier League",IMCompName:"*England Premier League"},
	IMLeagueId_199:{SCCompId:633,SCCompName:"Eerste Divisie",IMCompName:"Netherlands Eerste Divisie"},
	IMLeagueId_207:{SCCompId:351,SCCompName:"National League",IMCompName:"England National League"},
	IMLeagueId_209:{SCCompId:358,SCCompName:"League One",IMCompName:"England League 1"},
	IMLeagueId_213:{SCCompId:503,SCCompName:"Premier Division",IMCompName:"Ireland Premier Division"},
	IMLeagueId_237:{SCCompId:414,SCCompName:"National 1",IMCompName:"France Championnat National"},
	IMLeagueId_245:{SCCompId:287,SCCompName:"CSL",IMCompName:"China Super League"},
	IMLeagueId_246:{SCCompId:323,SCCompName:"Fortuna Liga",IMCompName:"Czech Republic First League"},
	IMLeagueId_247:{SCCompId:694,SCCompName:"I Liga",IMCompName:"Poland 1st Division"},
	IMLeagueId_250:{SCCompId:830,SCCompName:"Super League",IMCompName:"Switzerland Super League"},
	IMLeagueId_251:{SCCompId:797,SCCompName:"Segunda División",IMCompName:"Spain La Liga 2"},
	IMLeagueId_252:{SCCompId:426,SCCompName:"Bundesliga",IMCompName:"*Germany Bundesliga 1"},
	IMLeagueId_255:{SCCompId:412,SCCompName:"Ligue 1",IMCompName:"France Ligue 1"},
	IMLeagueId_257:{SCCompId:750,SCCompName:"Premiership",IMCompName:"Scotland Premiership"},
	IMLeagueId_258:{SCCompId:284,SCCompName:"Primera División",IMCompName:"Chile Primera Division"},
	IMLeagueId_259:{SCCompId:869,SCCompName:"MLS",IMCompName:"USA Major League Soccer"},
	IMLeagueId_264:{SCCompId:168,SCCompName:"Bundesliga",IMCompName:"Austria Bundesliga"},
	IMLeagueId_265:{SCCompId:401,SCCompName:"Ykkönen",IMCompName:"Finland Ykkonen"},
	IMLeagueId_266:{SCCompId:359,SCCompName:"League Two",IMCompName:"England League 2"},
	IMLeagueId_268:{SCCompId:534,SCCompName:"J1 League",IMCompName:"Japan J-League Division 1"},
	IMLeagueId_269:{SCCompId:328,SCCompName:"1st Division",IMCompName:"Denmark 1st Division"},
	IMLeagueId_270:{SCCompId:665,SCCompName:"Obos Ligaen",IMCompName:"Norway 1st Division"},
	IMLeagueId_271:{SCCompId:108,SCCompName:"UEFA Champions League",IMCompName:"*UEFA Champions League"},
	IMLeagueId_318:{SCCompId:617,SCCompName:"Liga MX",IMCompName:"Mexico Primera Division"},
	IMLeagueId_437:{SCCompId:317,SCCompName:"FNL",IMCompName:"Czech Republic National Football League"},
	IMLeagueId_447:{SCCompId:789,SCCompName:"PSL",IMCompName:"South Africa Premiership"},
	IMLeagueId_493:{SCCompId:744,SCCompName:"Championship",IMCompName:"Scotland Championship"},
	IMLeagueId_613:{SCCompId:879,SCCompName:"Primera División",IMCompName:"Uruguay Primera Division"},
	IMLeagueId_875:{SCCompId:635,SCCompName:"Eredivisie",IMCompName:"Netherlands Eredivisie"},
	IMLeagueId_987:{SCCompId:255,SCCompName:"Serie A",IMCompName:"Brazil Serie A"},
	IMLeagueId_1093:{SCCompId:9,SCCompName:"Friendlies",IMCompName:"International Friendly"},
	IMLeagueId_1303:{SCCompId:119,SCCompName:"WC Qualification Europe",IMCompName:"FIFA World Cup Europe Qualifiers"},
	IMLeagueId_1829:{SCCompId:348,SCCompName:"Community Shield",IMCompName:"England FA Community Shield"},
	IMLeagueId_2019:{SCCompId:108,SCCompName:"UEFA Champions League",IMCompName:"UEFA Champions League Qualifiers"},
	IMLeagueId_2020:{SCCompId:109,SCCompName:"UEFA Europa League",IMCompName:"UEFA Europa League Qualifiers"},
	IMLeagueId_2033:{SCCompId:109,SCCompName:"UEFA Europa League",IMCompName:"UEFA Europa League Qualifiers - Playoff"},
	IMLeagueId_2104:{SCCompId:335,SCCompName:"Superliga",IMCompName:"Denmark Super League"},
	IMLeagueId_2144:{SCCompId:692,SCCompName:"Ekstraklasa",IMCompName:"Poland Ekstraklasa"},
	IMLeagueId_2264:{SCCompId:198,SCCompName:"First Division A",IMCompName:"Belgium First Division A"},
	IMLeagueId_2820:{SCCompId:356,SCCompName:"Carabao Cup",IMCompName:"England League Cup"},
	IMLeagueId_3108:{SCCompId:355,SCCompName:"Papa John’s EFL Trophy",IMCompName:"England League Trophy"},
	IMLeagueId_3315:{SCCompId:90,SCCompName:"WC Qualification South America",IMCompName:"FIFA World Cup South America Qualifiers"},
	IMLeagueId_7614:{SCCompId:166,SCCompName:"2. Liga",IMCompName:"Austria 2nd League"},
	IMLeagueId_10106:{SCCompId:1414,SCCompName:"USL Championship",IMCompName:"United Soccer League Championship"},
	IMLeagueId_16081:{SCCompId:615,SCCompName:"Liga de Expansión MX",IMCompName:"Mexico Liga Expansion MX"},
	IMLeagueId_24427:{SCCompId:146,SCCompName:"Liga Profesional de Fútbol",IMCompName:"Argentina Liga Profesional"},
}

//IM 隊伍id(TeamId) 對應 SCTeamId
export const IMTeamIdSCTeam = {
	IMTeamId_8:{SCTeamId:3158,SCTeamName:"Roma",IMTeamName:"AS Roma"},
	IMTeamId_15:{SCTeamId:7457,SCTeamName:"AGF",IMTeamName:"AGF Aarhus"},
	IMTeamId_16:{SCTeamId:7454,SCTeamName:"AaB",IMTeamName:"Aalborg BK"},
	IMTeamId_23:{SCTeamId:7114,SCTeamName:"Haugesund",IMTeamName:"FK Haugesund"},
	IMTeamId_24:{SCTeamId:7098,SCTeamName:"Molde",IMTeamName:"Molde FK"},
	IMTeamId_42:{SCTeamId:9618,SCTeamName:"Académica",IMTeamName:"Academica Coimbra"},
	IMTeamId_45:{SCTeamId:4862,SCTeamName:"HIFK",IMTeamName:"HIFK Soccer"},
	IMTeamId_46:{SCTeamId:4784,SCTeamName:"Lahti",IMTeamName:"FC Lahti"},
	IMTeamId_55:{SCTeamId:737,SCTeamName:"Burgos",IMTeamName:"Burgos CF"},
	IMTeamId_61:{SCTeamId:6709,SCTeamName:"Malmö FF",IMTeamName:"Malmo FF"},
	IMTeamId_62:{SCTeamId:6713,SCTeamName:"Djurgården",IMTeamName:"Djurgardens IF"},
	IMTeamId_66:{SCTeamId:6711,SCTeamName:"Kalmar",IMTeamName:"Kalmar FF"},
	IMTeamId_69:{SCTeamId:6715,SCTeamName:"Trelleborg",IMTeamName:"Trelleborg FF"},
	IMTeamId_70:{SCTeamId:6714,SCTeamName:"Örgryte",IMTeamName:"Orgryte IS"},
	IMTeamId_73:{SCTeamId:4489,SCTeamName:"Beşiktaş",IMTeamName:"Besiktas JK"},
	IMTeamId_83:{SCTeamId:6415,SCTeamName:"Neuchâtel Xamax",IMTeamName:"Neuchatel Xamax FC"},
	IMTeamId_87:{SCTeamId:2445,SCTeamName:"Stuttgart",IMTeamName:"VfB Stuttgart"},
	IMTeamId_88:{SCTeamId:2500,SCTeamName:"Union Berlin",IMTeamName:"FC Union Berlin"},
	IMTeamId_89:{SCTeamId:3186,SCTeamName:"Vicenza",IMTeamName:"LR Vicenza Virtus"},
	IMTeamId_92:{SCTeamId:3426,SCTeamName:"Pordenone",IMTeamName:"Pordenone Calcio"},
	IMTeamId_95:{SCTeamId:701,SCTeamName:"Eibar",IMTeamName:"SD Eibar"},
	IMTeamId_96:{SCTeamId:678,SCTeamName:"Athletic Bilbao",IMTeamName:"Athletic Bilbao"},
	IMTeamId_97:{SCTeamId:3793,SCTeamName:"Le Havre",IMTeamName:"Le Havre AC"},
	IMTeamId_98:{SCTeamId:3773,SCTeamName:"Lens",IMTeamName:"RC Lens"},
	IMTeamId_99:{SCTeamId:1613,SCTeamName:"Newcastle United",IMTeamName:"Newcastle United"},
	IMTeamId_100:{SCTeamId:1641,SCTeamName:"Preston North End",IMTeamName:"Preston North End"},
	IMTeamId_101:{SCTeamId:3160,SCTeamName:"Parma",IMTeamName:"Parma"},
	IMTeamId_103:{SCTeamId:8154,SCTeamName:"Bohemians",IMTeamName:"Bohemian FC Dublin"},
	IMTeamId_105:{SCTeamId:9615,SCTeamName:"Moreirense",IMTeamName:"Moreirense"},
	IMTeamId_106:{SCTeamId:9632,SCTeamName:"Chaves",IMTeamName:"GD Chaves"},
	IMTeamId_115:{SCTeamId:12059,SCTeamName:"Colón",IMTeamName:"Club Atletico Colon"},
	IMTeamId_332:{SCTeamId:3192,SCTeamName:"Salernitana",IMTeamName:"Salernitana"},
	IMTeamId_334:{SCTeamId:1610,SCTeamName:"Chelsea",IMTeamName:"Chelsea"},
	IMTeamId_335:{SCTeamId:1619,SCTeamName:"Southampton",IMTeamName:"Southampton"},
	IMTeamId_336:{SCTeamId:3254,SCTeamName:"Frosinone",IMTeamName:"Frosinone"},
	IMTeamId_337:{SCTeamId:3205,SCTeamName:"Spezia",IMTeamName:"AC Spezia"},
	IMTeamId_338:{SCTeamId:679,SCTeamName:"Atlético Madrid",IMTeamName:"Atletico de Madrid"},
	IMTeamId_339:{SCTeamId:682,SCTeamName:"Villarreal",IMTeamName:"Villarreal CF"},
	IMTeamId_340:{SCTeamId:846,SCTeamName:"Granada",IMTeamName:"Granada CF"},
	IMTeamId_341:{SCTeamId:683,SCTeamName:"Málaga",IMTeamName:"Malaga CF"},
	IMTeamId_342:{SCTeamId:3204,SCTeamName:"SPAL",IMTeamName:"Spal 2013"},
	IMTeamId_343:{SCTeamId:3208,SCTeamName:"Cittadella",IMTeamName:"AS Cittadella"},
	IMTeamId_344:{SCTeamId:3207,SCTeamName:"Pisa",IMTeamName:"Pisa"},
	IMTeamId_347:{SCTeamId:691,SCTeamName:"Espanyol",IMTeamName:"RCD Espanyol"},
	IMTeamId_348:{SCTeamId:3167,SCTeamName:"Brescia",IMTeamName:"Brescia"},
	IMTeamId_349:{SCTeamId:3182,SCTeamName:"Ternana",IMTeamName:"Ternana"},
	IMTeamId_352:{SCTeamId:3188,SCTeamName:"Ascoli",IMTeamName:"Ascoli"},
	IMTeamId_355:{SCTeamId:3219,SCTeamName:"Benevento",IMTeamName:"Benevento"},
	IMTeamId_358:{SCTeamId:3179,SCTeamName:"Perugia",IMTeamName:"Perugia"},
	IMTeamId_359:{SCTeamId:3194,SCTeamName:"Hellas Verona",IMTeamName:"Hellas Verona"},
	IMTeamId_360:{SCTeamId:3799,SCTeamName:"Angers SCO",IMTeamName:"Angers SCO"},
	IMTeamId_364:{SCTeamId:1629,SCTeamName:"Wolverhampton Wanderers",IMTeamName:"Wolverhampton Wanderers"},
	IMTeamId_365:{SCTeamId:1673,SCTeamName:"Huddersfield Town",IMTeamName:"Huddersfield Town"},
	IMTeamId_368:{SCTeamId:2454,SCTeamName:"Borussia M'gladbach",IMTeamName:"Borussia Monchengladbach"},
	IMTeamId_369:{SCTeamId:2462,SCTeamName:"Eintracht Frankfurt",IMTeamName:"Eintracht Frankfurt"},
	IMTeamId_372:{SCTeamId:12803,SCTeamName:"Gamba Osaka",IMTeamName:"Gamba Osaka"},
	IMTeamId_377:{SCTeamId:12812,SCTeamName:"Kawasaki Frontale",IMTeamName:"Kawasaki Frontale"},
	IMTeamId_386:{SCTeamId:11242,SCTeamName:"Slavia Praha",IMTeamName:"SK Slavia Praha"},
	IMTeamId_387:{SCTeamId:11245,SCTeamName:"FASTAV Zlín",IMTeamName:"FC Fastav Zlin"},
	IMTeamId_395:{SCTeamId:27,SCTeamName:"Den Bosch",IMTeamName:"FC Den Bosch"},
	IMTeamId_405:{SCTeamId:9417,SCTeamName:"Dinamo Zagreb",IMTeamName:"NK Dinamo Zagreb"},
	IMTeamId_424:{SCTeamId:12136,SCTeamName:"Atlético Tucumán",IMTeamName:"Club Atletico Tucuman SC"},
	IMTeamId_428:{SCTeamId:12071,SCTeamName:"San Lorenzo",IMTeamName:"San Lorenzo"},
	IMTeamId_429:{SCTeamId:12295,SCTeamName:"Universidad Católica",IMTeamName:"CD Universidad Catolica"},
	IMTeamId_432:{SCTeamId:1652,SCTeamName:"Walsall",IMTeamName:"Walsall"},
	IMTeamId_433:{SCTeamId:1658,SCTeamName:"Port Vale",IMTeamName:"Port Vale"},
	IMTeamId_435:{SCTeamId:5067,SCTeamName:"Gent",IMTeamName:"KAA Gent"},
	IMTeamId_437:{SCTeamId:1752,SCTeamName:"Harrogate Town",IMTeamName:"Harrogate Town"},
	IMTeamId_439:{SCTeamId:5105,SCTeamName:"Kortrijk",IMTeamName:"KV Kortrijk"},
	IMTeamId_440:{SCTeamId:5120,SCTeamName:"Union Saint-Gilloise",IMTeamName:"Union Saint Gilloise"},
	IMTeamId_442:{SCTeamId:5083,SCTeamName:"Standard Liège",IMTeamName:"Standard Liege"},
	IMTeamId_444:{SCTeamId:10846,SCTeamName:"Derry City",IMTeamName:"Derry City FC"},
	IMTeamId_446:{SCTeamId:8822,SCTeamName:"Liefering",IMTeamName:"FC Liefering"},
	IMTeamId_449:{SCTeamId:1680,SCTeamName:"Lincoln City",IMTeamName:"Lincoln City"},
	IMTeamId_452:{SCTeamId:684,SCTeamName:"Real Betis",IMTeamName:"Real Betis"},
	IMTeamId_488:{SCTeamId:9311,SCTeamName:"Ludogorets",IMTeamName:"PFC Ludogorets Razgrad"},
	IMTeamId_501:{SCTeamId:7302,SCTeamName:"Stjørdals-Blink",IMTeamName:"Stjordals Blink"},
	IMTeamId_512:{SCTeamId:6716,SCTeamName:"AIK",IMTeamName:"AIK Solna"},
	IMTeamId_513:{SCTeamId:6708,SCTeamName:"Halmstad",IMTeamName:"Halmstads BK"},
	IMTeamId_514:{SCTeamId:6726,SCTeamName:"IFK Norrköping",IMTeamName:"IFK Norrkoping"},
	IMTeamId_515:{SCTeamId:6849,SCTeamName:"Jönköpings Södra",IMTeamName:"Jonkopings Sodra IF"},
	IMTeamId_516:{SCTeamId:7488,SCTeamName:"Vendsyssel",IMTeamName:"Vendsyssel FF"},
	IMTeamId_517:{SCTeamId:7452,SCTeamName:"København",IMTeamName:"FC Kobenhavn"},
	IMTeamId_524:{SCTeamId:696,SCTeamName:"Deportivo Alavés",IMTeamName:"Deportivo Alaves"},
	IMTeamId_527:{SCTeamId:4551,SCTeamName:"Kasımpaşa",IMTeamName:"Kasimpasa"},
	IMTeamId_528:{SCTeamId:4498,SCTeamName:"Konyaspor",IMTeamName:"Konyaspor"},
	IMTeamId_539:{SCTeamId:680,SCTeamName:"Sevilla",IMTeamName:"Sevilla FC"},
	IMTeamId_540:{SCTeamId:692,SCTeamName:"Celta de Vigo",IMTeamName:"Celta Vigo"},
	IMTeamId_543:{SCTeamId:3815,SCTeamName:"Pau",IMTeamName:"Pau FC"},
	IMTeamId_544:{SCTeamId:5068,SCTeamName:"Anderlecht",IMTeamName:"RSC Anderlecht"},
	IMTeamId_545:{SCTeamId:5071,SCTeamName:"Charleroi",IMTeamName:"Royal Charleroi SC"},
	IMTeamId_552:{SCTeamId:1625,SCTeamName:"Manchester City",IMTeamName:"Manchester City"},
	IMTeamId_557:{SCTeamId:5819,SCTeamName:"Chapecoense",IMTeamName:"Associacao Chapecoense de Futebol"},
	IMTeamId_561:{SCTeamId:12063,SCTeamName:"Lanús",IMTeamName:"Club Atletico Lanus"},
	IMTeamId_572:{SCTeamId:5649,SCTeamName:"Grêmio",IMTeamName:"Gremio Foot-Ball Porto Alegrense"},
	IMTeamId_575:{SCTeamId:12084,SCTeamName:"Godoy Cruz",IMTeamName:"Godoy Cruz Antonio Tomba"},
	IMTeamId_598:{SCTeamId:13529,SCTeamName:"Arka Gdynia",IMTeamName:"Arka Gdynia"},
	IMTeamId_599:{SCTeamId:13530,SCTeamName:"Piast Gliwice",IMTeamName:"Piast Gliwice"},
	IMTeamId_604:{SCTeamId:7460,SCTeamName:"OB",IMTeamName:"Odense BK"},
	IMTeamId_608:{SCTeamId:4513,SCTeamName:"Sivasspor",IMTeamName:"Sivasspor"},
	IMTeamId_610:{SCTeamId:4546,SCTeamName:"Giresunspor",IMTeamName:"Giresunspor"},
	IMTeamId_612:{SCTeamId:8758,SCTeamName:"Blau-Weiß Linz",IMTeamName:"FC Blau Weiss Linz"},
	IMTeamId_613:{SCTeamId:8791,SCTeamName:"Horn",IMTeamName:"SV Horn"},
	IMTeamId_615:{SCTeamId:8746,SCTeamName:"Austria Lustenau",IMTeamName:"Austria Lustenau"},
	IMTeamId_616:{SCTeamId:8806,SCTeamName:"Floridsdorfer AC",IMTeamName:"Floridsdorfer AC"},
	IMTeamId_617:{SCTeamId:2495,SCTeamName:"St. Pauli",IMTeamName:"FC St. Pauli"},
	IMTeamId_618:{SCTeamId:2658,SCTeamName:"Heidenheim",IMTeamName:"1.FC Heidenheim 1846"},
	IMTeamId_620:{SCTeamId:2478,SCTeamName:"Dynamo Dresden",IMTeamName:"Dynamo Dresden"},
	IMTeamId_621:{SCTeamId:2694,SCTeamName:"Sandhausen",IMTeamName:"SV Sandhausen"},
	IMTeamId_623:{SCTeamId:13544,SCTeamName:"Stal Mielec",IMTeamName:"Stal Mielec"},
	IMTeamId_624:{SCTeamId:13597,SCTeamName:"Chrobry Głogów",IMTeamName:"MZKS Chrobry Glogow"},
	IMTeamId_625:{SCTeamId:13512,SCTeamName:"Górnik Zabrze",IMTeamName:"Gornik Zabrze"},
	IMTeamId_626:{SCTeamId:8510,SCTeamName:"Hearts",IMTeamName:"Heart of Midlothian FC"},
	IMTeamId_627:{SCTeamId:8519,SCTeamName:"Partick Thistle",IMTeamName:"Partick Thistle FC"},
	IMTeamId_628:{SCTeamId:11248,SCTeamName:"Teplice",IMTeamName:"FK Teplice"},
	IMTeamId_629:{SCTeamId:11327,SCTeamName:"Slovácko",IMTeamName:"1. FC Slovacko"},
	IMTeamId_630:{SCTeamId:6734,SCTeamName:"Falkenberg",IMTeamName:"Falkenbergs FF"},
	IMTeamId_631:{SCTeamId:6732,SCTeamName:"GAIS",IMTeamName:"GAIS Goteborg"},
	IMTeamId_632:{SCTeamId:4991,SCTeamName:"SJK",IMTeamName:"Seinajoen JK"},
	IMTeamId_633:{SCTeamId:687,SCTeamName:"Real Sociedad",IMTeamName:"Real Sociedad"},
	IMTeamId_637:{SCTeamId:2491,SCTeamName:"Paderborn",IMTeamName:"SC Paderborn 07"},
	IMTeamId_640:{SCTeamId:6407,SCTeamName:"Basel",IMTeamName:"FC Basel"},
	IMTeamId_642:{SCTeamId:3791,SCTeamName:"Sedan",IMTeamName:"CS Sedan Ardennes"},
	IMTeamId_644:{SCTeamId:3854,SCTeamName:"Avranches",IMTeamName:"US Avranches"},
	IMTeamId_647:{SCTeamId:3904,SCTeamName:"Dunkerque",IMTeamName:"USL Dunkerque"},
	IMTeamId_648:{SCTeamId:3794,SCTeamName:"Châteauroux",IMTeamName:"La Berrichonne de Chateauroux"},
	IMTeamId_649:{SCTeamId:3838,SCTeamName:"Boulogne",IMTeamName:"US Boulogne"},
	IMTeamId_650:{SCTeamId:3846,SCTeamName:"Paris",IMTeamName:"Paris FC"},
	IMTeamId_651:{SCTeamId:3980,SCTeamName:"Concarneau US",IMTeamName:"US Concarneau"},
	IMTeamId_653:{SCTeamId:3796,SCTeamName:"Créteil",IMTeamName:"US Creteil-Lusitanos"},
	IMTeamId_656:{SCTeamId:3790,SCTeamName:"Niort",IMTeamName:"Chamois Niortais FC"},
	IMTeamId_657:{SCTeamId:3802,SCTeamName:"Reims",IMTeamName:"Stade De Reims"},
	IMTeamId_658:{SCTeamId:702,SCTeamName:"Elche",IMTeamName:"Elche"},
	IMTeamId_659:{SCTeamId:708,SCTeamName:"Almería",IMTeamName:"UD Almeria"},
	IMTeamId_660:{SCTeamId:3789,SCTeamName:"Amiens SC",IMTeamName:"Amiens SC"},
	IMTeamId_661:{SCTeamId:3781,SCTeamName:"Ajaccio",IMTeamName:"AC Ajaccio"},
	IMTeamId_663:{SCTeamId:3813,SCTeamName:"Nîmes",IMTeamName:"Nimes"},
	IMTeamId_664:{SCTeamId:3769,SCTeamName:"Auxerre",IMTeamName:"AJ Auxerre"},
	IMTeamId_665:{SCTeamId:3925,SCTeamName:"Orléans",IMTeamName:"US Orleans"},
	IMTeamId_666:{SCTeamId:3829,SCTeamName:"Red Star",IMTeamName:"Red Star Saint Ouen"},
	IMTeamId_668:{SCTeamId:3797,SCTeamName:"Clermont",IMTeamName:"Clermont Foot"},
	IMTeamId_670:{SCTeamId:3814,SCTeamName:"Valenciennes",IMTeamName:"Valenciennes FC"},
	IMTeamId_671:{SCTeamId:3824,SCTeamName:"Bourg en Bresse 01",IMTeamName:"Bourg en Bresse Peronnas 01"},
	IMTeamId_672:{SCTeamId:3768,SCTeamName:"Sochaux",IMTeamName:"FC Sochaux Montbeliard"},
	IMTeamId_674:{SCTeamId:11241,SCTeamName:"Sparta Praha",IMTeamName:"AC Sparta Praha"},
	IMTeamId_675:{SCTeamId:7462,SCTeamName:"Randers",IMTeamName:"Randers FC"},
	IMTeamId_676:{SCTeamId:7451,SCTeamName:"Esbjerg",IMTeamName:"Esbjerg FB"},
	IMTeamId_677:{SCTeamId:8765,SCTeamName:"WSG Swarovski Tirol",IMTeamName:"WSG Swarovski Tirol"},
	IMTeamId_678:{SCTeamId:2446,SCTeamName:"Bayer Leverkusen",IMTeamName:"Bayer 04 Leverkusen"},
	IMTeamId_679:{SCTeamId:2449,SCTeamName:"Schalke 04",IMTeamName:"FC Schalke 04"},
	IMTeamId_680:{SCTeamId:13510,SCTeamName:"Lech Poznań",IMTeamName:"Lech Poznan"},
	IMTeamId_681:{SCTeamId:13547,SCTeamName:"Korona Kielce",IMTeamName:"Korona Kielce"},
	IMTeamId_682:{SCTeamId:13524,SCTeamName:"Podbeskidzie Bielsko-Biała",IMTeamName:"Podbeskidzie Bielsko Biala"},
	IMTeamId_683:{SCTeamId:13585,SCTeamName:"Miedź Legnica",IMTeamName:"Miedz Legnica"},
	IMTeamId_687:{SCTeamId:8149,SCTeamName:"Waterford FC",IMTeamName:"Waterford FC"},
	IMTeamId_689:{SCTeamId:10529,SCTeamName:"Cardiff City",IMTeamName:"Cardiff City"},
	IMTeamId_691:{SCTeamId:3766,SCTeamName:"Olympique Lyonnais",IMTeamName:"Olympique Lyonnais"},
	IMTeamId_692:{SCTeamId:8150,SCTeamName:"Drogheda United",IMTeamName:"Drogheda United FC"},
	IMTeamId_693:{SCTeamId:8160,SCTeamName:"Sligo Rovers",IMTeamName:"Sligo Rovers FC"},
	IMTeamId_696:{SCTeamId:8161,SCTeamName:"Finn Harps",IMTeamName:"Finn Harps FC"},
	IMTeamId_697:{SCTeamId:8524,SCTeamName:"Ross County",IMTeamName:"Ross County FC"},
	IMTeamId_698:{SCTeamId:8521,SCTeamName:"Inverness CT",IMTeamName:"Inverness CT"},
	IMTeamId_700:{SCTeamId:8163,SCTeamName:"Dundalk",IMTeamName:"Dundalk FC"},
	IMTeamId_701:{SCTeamId:8152,SCTeamName:"Shamrock Rovers",IMTeamName:"Shamrock Rovers FC"},
	IMTeamId_705:{SCTeamId:9617,SCTeamName:"Vitória Guimarães",IMTeamName:"Vitoria Guimaraes"},
	IMTeamId_707:{SCTeamId:12072,SCTeamName:"Talleres Córdoba",IMTeamName:"Talleres Cordoba"},
	IMTeamId_711:{SCTeamId:7944,SCTeamName:"Houston Dynamo",IMTeamName:"Houston Dynamo"},
	IMTeamId_714:{SCTeamId:12062,SCTeamName:"Independiente",IMTeamName:"CA Independiente"},
	IMTeamId_717:{SCTeamId:12822,SCTeamName:"Shonan Bellmare",IMTeamName:"Shonan Bellmare"},
	IMTeamId_722:{SCTeamId:12814,SCTeamName:"Avispa Fukuoka",IMTeamName:"Avispa Fukuoka"},
	IMTeamId_726:{SCTeamId:12802,SCTeamName:"Oita Trinita",IMTeamName:"Oita Trinita"},
	IMTeamId_729:{SCTeamId:12817,SCTeamName:"Yokohama",IMTeamName:"Yokohama FC"},
	IMTeamId_735:{SCTeamId:9138,SCTeamName:"Changchun Yatai",IMTeamName:"Changchun Yatai FC(N)"},
	IMTeamId_744:{SCTeamId:12801,SCTeamName:"Nagoya Grampus",IMTeamName:"Nagoya Grampus"},
	IMTeamId_745:{SCTeamId:9638,SCTeamName:"Portimonense",IMTeamName:"Portimonense SC"},
	IMTeamId_746:{SCTeamId:9635,SCTeamName:"Leixões",IMTeamName:"Leixoes SC"},
	IMTeamId_747:{SCTeamId:2459,SCTeamName:"Arminia Bielefeld",IMTeamName:"Arminia Bielefeld"},
	IMTeamId_748:{SCTeamId:2469,SCTeamName:"Greuther Fürth",IMTeamName:"SpVgg Greuther Furth"},
	IMTeamId_749:{SCTeamId:2472,SCTeamName:"Karlsruher SC",IMTeamName:"Karlsruher SC"},
	IMTeamId_751:{SCTeamId:2458,SCTeamName:"Nürnberg",IMTeamName:"FC Nurnberg"},
	IMTeamId_752:{SCTeamId:8509,SCTeamName:"Rangers",IMTeamName:"Glasgow Rangers"},
	IMTeamId_753:{SCTeamId:8508,SCTeamName:"Celtic",IMTeamName:"Celtic FC"},
	IMTeamId_762:{SCTeamId:2452,SCTeamName:"Hansa Rostock",IMTeamName:"Hansa Rostock"},
	IMTeamId_770:{SCTeamId:2480,SCTeamName:"Jahn Regensburg",IMTeamName:"SSV Jahn Regensburg"},
	IMTeamId_771:{SCTeamId:2496,SCTeamName:"Holstein Kiel",IMTeamName:"Holstein Kiel"},
	IMTeamId_775:{SCTeamId:4622,SCTeamName:"Yeni Malatyaspor",IMTeamName:"Yeni Malatyaspor"},
	IMTeamId_776:{SCTeamId:4522,SCTeamName:"Göztepe",IMTeamName:"Goztepe AS"},
	IMTeamId_778:{SCTeamId:4787,SCTeamName:"HJK",IMTeamName:"HJK Helsinki"},
	IMTeamId_779:{SCTeamId:4775,SCTeamName:"Inter Turku",IMTeamName:"Inter Turku"},
	IMTeamId_780:{SCTeamId:4788,SCTeamName:"KuPS",IMTeamName:"KuPS"},
	IMTeamId_781:{SCTeamId:4854,SCTeamName:"Ilves",IMTeamName:"Ilves Tampere"},
	IMTeamId_782:{SCTeamId:4779,SCTeamName:"RoPS",IMTeamName:"RoPS Rovaniemi"},
	IMTeamId_784:{SCTeamId:4510,SCTeamName:"Kayserispor",IMTeamName:"Kayserispor"},
	IMTeamId_785:{SCTeamId:4555,SCTeamName:"Alanyaspor",IMTeamName:"Alanyaspor"},
	IMTeamId_786:{SCTeamId:3865,SCTeamName:"Quevilly Rouen",IMTeamName:"US Quevilly Rouen"},
	IMTeamId_788:{SCTeamId:3795,SCTeamName:"Troyes",IMTeamName:"ES Troyes AC"},
	IMTeamId_789:{SCTeamId:3803,SCTeamName:"Brest",IMTeamName:"Stade Brestois"},
	IMTeamId_791:{SCTeamId:2460,SCTeamName:"Mainz 05",IMTeamName:"FSV Mainz 05"},
	IMTeamId_792:{SCTeamId:2975,SCTeamName:"RB Leipzig",IMTeamName:"RB Leipzig"},
	IMTeamId_794:{SCTeamId:2443,SCTeamName:"Werder Bremen",IMTeamName:"Werder Bremen"},
	IMTeamId_795:{SCTeamId:2457,SCTeamName:"Hertha BSC",IMTeamName:"Hertha BSC Berlin"},
	IMTeamId_796:{SCTeamId:2520,SCTeamName:"Darmstadt 98",IMTeamName:"SV Darmstadt 98"},
	IMTeamId_797:{SCTeamId:2453,SCTeamName:"Freiburg",IMTeamName:"SC Freiburg"},
	IMTeamId_798:{SCTeamId:2447,SCTeamName:"Borussia Dortmund",IMTeamName:"Borussia Dortmund"},
	IMTeamId_799:{SCTeamId:2463,SCTeamName:"Köln",IMTeamName:"FC Koln"},
	IMTeamId_804:{SCTeamId:8736,SCTeamName:"Austria Wien",IMTeamName:"Austria Wien"},
	IMTeamId_806:{SCTeamId:4791,SCTeamName:"Oulu",IMTeamName:"AC Oulu"},
	IMTeamId_807:{SCTeamId:4812,SCTeamName:"Gnistan",IMTeamName:"Gnistan Helsinki"},
	IMTeamId_808:{SCTeamId:4776,SCTeamName:"Haka",IMTeamName:"FC Haka"},
	IMTeamId_809:{SCTeamId:4796,SCTeamName:"Honka",IMTeamName:"FC Honka Espoo"},
	IMTeamId_811:{SCTeamId:4845,SCTeamName:"KPV",IMTeamName:"KPV"},
	IMTeamId_812:{SCTeamId:1698,SCTeamName:"Carlisle United",IMTeamName:"Carlisle United"},
	IMTeamId_813:{SCTeamId:1768,SCTeamName:"Newport County",IMTeamName:"Newport County AFC"},
	IMTeamId_814:{SCTeamId:1701,SCTeamName:"Barnet",IMTeamName:"Barnet"},
	IMTeamId_815:{SCTeamId:1675,SCTeamName:"Grimsby Town",IMTeamName:"Grimsby Town"},
	IMTeamId_816:{SCTeamId:1671,SCTeamName:"Doncaster Rovers",IMTeamName:"Doncaster Rovers"},
	IMTeamId_817:{SCTeamId:1703,SCTeamName:"Exeter City",IMTeamName:"Exeter City"},
	IMTeamId_818:{SCTeamId:1686,SCTeamName:"Cheltenham Town",IMTeamName:"Cheltenham Town"},
	IMTeamId_819:{SCTeamId:1657,SCTeamName:"Hartlepool United",IMTeamName:"Hartlepool United"},
	IMTeamId_820:{SCTeamId:1707,SCTeamName:"Accrington Stanley",IMTeamName:"Accrington Stanley"},
	IMTeamId_821:{SCTeamId:1660,SCTeamName:"Luton Town",IMTeamName:"Luton Town"},
	IMTeamId_822:{SCTeamId:1689,SCTeamName:"Cambridge United",IMTeamName:"Cambridge United"},
	IMTeamId_823:{SCTeamId:1726,SCTeamName:"Crawley Town",IMTeamName:"Crawley Town"},
	IMTeamId_824:{SCTeamId:1677,SCTeamName:"Notts County",IMTeamName:"Notts County"},
	IMTeamId_825:{SCTeamId:1690,SCTeamName:"Leyton Orient",IMTeamName:"Leyton Orient"},
	IMTeamId_826:{SCTeamId:1664,SCTeamName:"Blackpool",IMTeamName:"Blackpool"},
	IMTeamId_827:{SCTeamId:1662,SCTeamName:"Colchester United",IMTeamName:"Colchester United"},
	IMTeamId_829:{SCTeamId:1622,SCTeamName:"Portsmouth",IMTeamName:"Portsmouth"},
	IMTeamId_830:{SCTeamId:1704,SCTeamName:"Morecambe",IMTeamName:"Morecambe"},
	IMTeamId_831:{SCTeamId:1678,SCTeamName:"Wycombe Wanderers",IMTeamName:"Wycombe Wanderers"},
	IMTeamId_832:{SCTeamId:1649,SCTeamName:"Plymouth Argyle",IMTeamName:"Plymouth Argyle"},
	IMTeamId_833:{SCTeamId:1645,SCTeamName:"Crewe Alexandra",IMTeamName:"Crewe Alexandra"},
	IMTeamId_834:{SCTeamId:1682,SCTeamName:"Yeovil Town",IMTeamName:"Yeovil Town"},
	IMTeamId_835:{SCTeamId:1705,SCTeamName:"Stevenage",IMTeamName:"Stevenage FC"},
	IMTeamId_836:{SCTeamId:1647,SCTeamName:"Derby County",IMTeamName:"Derby County"},
	IMTeamId_837:{SCTeamId:1616,SCTeamName:"Fulham",IMTeamName:"Fulham"},
	IMTeamId_838:{SCTeamId:1669,SCTeamName:"Brentford",IMTeamName:"Brentford"},
	IMTeamId_839:{SCTeamId:1663,SCTeamName:"Barnsley",IMTeamName:"Barnsley"},
	IMTeamId_840:{SCTeamId:1710,SCTeamName:"Burton Albion",IMTeamName:"Burton Albion"},
	IMTeamId_841:{SCTeamId:1618,SCTeamName:"Birmingham City",IMTeamName:"Birmingham City"},
	IMTeamId_842:{SCTeamId:1621,SCTeamName:"Blackburn Rovers",IMTeamName:"Blackburn Rovers"},
	IMTeamId_843:{SCTeamId:1614,SCTeamName:"Aston Villa",IMTeamName:"Aston Villa"},
	IMTeamId_844:{SCTeamId:1634,SCTeamName:"Ipswich Town",IMTeamName:"Ipswich Town"},
	IMTeamId_845:{SCTeamId:1666,SCTeamName:"Sheffield Wednesday",IMTeamName:"Sheffield Wednesday"},
	IMTeamId_846:{SCTeamId:1630,SCTeamName:"Leeds United",IMTeamName:"Leeds United"},
	IMTeamId_847:{SCTeamId:1626,SCTeamName:"Norwich City",IMTeamName:"Norwich City"},
	IMTeamId_848:{SCTeamId:1637,SCTeamName:"Reading",IMTeamName:"Reading"},
	IMTeamId_849:{SCTeamId:1635,SCTeamName:"Wigan Athletic",IMTeamName:"Wigan Athletic"},
	IMTeamId_850:{SCTeamId:1650,SCTeamName:"Queens Park Rangers",IMTeamName:"Queens Park Rangers"},
	IMTeamId_851:{SCTeamId:1642,SCTeamName:"Nottingham Forest",IMTeamName:"Nottingham Forest"},
	IMTeamId_852:{SCTeamId:1643,SCTeamName:"Rotherham United",IMTeamName:"Rotherham United"},
	IMTeamId_853:{SCTeamId:1627,SCTeamName:"West Bromwich Albion",IMTeamName:"West Bromwich Albion"},
	IMTeamId_855:{SCTeamId:1672,SCTeamName:"Hull City",IMTeamName:"Hull City"},
	IMTeamId_856:{SCTeamId:1639,SCTeamName:"Stoke City",IMTeamName:"Stoke City"},
	IMTeamId_857:{SCTeamId:1633,SCTeamName:"West Ham United",IMTeamName:"West Ham United"},
	IMTeamId_858:{SCTeamId:1632,SCTeamName:"Sunderland",IMTeamName:"Sunderland"},
	IMTeamId_861:{SCTeamId:8522,SCTeamName:"St. Johnstone",IMTeamName:"Saint Johnstone FC"},
	IMTeamId_862:{SCTeamId:8532,SCTeamName:"Hamilton Academical",IMTeamName:"Hamilton Academical FC"},
	IMTeamId_863:{SCTeamId:8516,SCTeamName:"Kilmarnock",IMTeamName:"Kilmarnock"},
	IMTeamId_864:{SCTeamId:8512,SCTeamName:"Motherwell",IMTeamName:"Motherwell FC"},
	IMTeamId_865:{SCTeamId:8517,SCTeamName:"Dundee",IMTeamName:"Dundee FC"},
	IMTeamId_867:{SCTeamId:707,SCTeamName:"Tenerife",IMTeamName:"Tenerife"},
	IMTeamId_868:{SCTeamId:7455,SCTeamName:"Midtjylland",IMTeamName:"FC Midtjylland"},
	IMTeamId_869:{SCTeamId:7458,SCTeamName:"Nordsjælland",IMTeamName:"FC Nordsjaelland"},
	IMTeamId_870:{SCTeamId:675,SCTeamName:"Real Madrid",IMTeamName:"Real Madrid"},
	IMTeamId_871:{SCTeamId:674,SCTeamName:"Valencia",IMTeamName:"Valencia CF"},
	IMTeamId_872:{SCTeamId:13513,SCTeamName:"Katowice",IMTeamName:"GKS Katowice"},
	IMTeamId_873:{SCTeamId:13647,SCTeamName:"Tychy 71",IMTeamName:"GKS Tychy"},
	IMTeamId_874:{SCTeamId:19830,SCTeamName:"Monaco",IMTeamName:"AS Monaco FC"},
	IMTeamId_875:{SCTeamId:3780,SCTeamName:"Toulouse",IMTeamName:"Toulouse FC"},
	IMTeamId_876:{SCTeamId:12289,SCTeamName:"Universidad de Chile",IMTeamName:"Universidad de Chile"},
	IMTeamId_877:{SCTeamId:11257,SCTeamName:"Mladá Boleslav",IMTeamName:"FK Mlada Boleslav"},
	IMTeamId_879:{SCTeamId:9613,SCTeamName:"Boavista",IMTeamName:"Boavista FC"},
	IMTeamId_880:{SCTeamId:9813,SCTeamName:"Tondela",IMTeamName:"CD Tondela"},
	IMTeamId_881:{SCTeamId:9609,SCTeamName:"Nacional",IMTeamName:"CD Nacional da Madeira"},
	IMTeamId_882:{SCTeamId:9611,SCTeamName:"Rio Ave",IMTeamName:"Rio Ave FC"},
	IMTeamId_883:{SCTeamId:6434,SCTeamName:"Lausanne Sport",IMTeamName:"FC Lausanne Sports"},
	IMTeamId_884:{SCTeamId:4528,SCTeamName:"Adana Demirspor",IMTeamName:"Adana Demirspor"},
	IMTeamId_885:{SCTeamId:17696,SCTeamName:"Vaduz",IMTeamName:"FC Vaduz"},
	IMTeamId_888:{SCTeamId:13625,SCTeamName:"Sandecja Nowy Sącz",IMTeamName:"Sandecja Nowy Sacz"},
	IMTeamId_891:{SCTeamId:13550,SCTeamName:"Zagłębie Sosnowiec",IMTeamName:"Zaglebie Sosnowiec"},
	IMTeamId_895:{SCTeamId:13536,SCTeamName:"Śląsk Wrocław",IMTeamName:"Slask Wroclaw"},
	IMTeamId_896:{SCTeamId:13511,SCTeamName:"Górnik Łęczna",IMTeamName:"Gornik Leczna"},
	IMTeamId_897:{SCTeamId:690,SCTeamName:"Real Valladolid",IMTeamName:"Real Valladolid"},
	IMTeamId_903:{SCTeamId:7095,SCTeamName:"Brann",IMTeamName:"Brann"},
	IMTeamId_904:{SCTeamId:7100,SCTeamName:"Viking",IMTeamName:"Viking FK"},
	IMTeamId_907:{SCTeamId:4786,SCTeamName:"TPS",IMTeamName:"TPS Turku"},
	IMTeamId_909:{SCTeamId:10183,SCTeamName:"Ferencváros",IMTeamName:"Ferencvarosi TC"},
	IMTeamId_911:{SCTeamId:13577,SCTeamName:"Stomil Olsztyn",IMTeamName:"OKS Stomil Olsztyn(N)"},
	IMTeamId_915:{SCTeamId:714,SCTeamName:"Las Palmas",IMTeamName:"Las Palmas"},
	IMTeamId_919:{SCTeamId:8749,SCTeamName:"Ried",IMTeamName:"SV Ried"},
	IMTeamId_920:{SCTeamId:22253,SCTeamName:"Wolfsberger AC",IMTeamName:"Wolfsberger AC"},
	IMTeamId_922:{SCTeamId:8756,SCTeamName:"St. Pölten",IMTeamName:"SKN St Polten"},
	IMTeamId_923:{SCTeamId:8768,SCTeamName:"Rheindorf Altach",IMTeamName:"SCR Altach"},
	IMTeamId_924:{SCTeamId:2451,SCTeamName:"Wolfsburg",IMTeamName:"VfL Wolfsburg"},
	IMTeamId_925:{SCTeamId:2444,SCTeamName:"Bayern München",IMTeamName:"Bayern Munchen"},
	IMTeamId_926:{SCTeamId:1651,SCTeamName:"Brighton",IMTeamName:"Brighton And Hove Albion"},
	IMTeamId_927:{SCTeamId:1655,SCTeamName:"Bristol City",IMTeamName:"Bristol City"},
	IMTeamId_929:{SCTeamId:1646,SCTeamName:"Burnley",IMTeamName:"Burnley"},
	IMTeamId_934:{SCTeamId:9623,SCTeamName:"Estoril",IMTeamName:"GD Estoril Praia"},
	IMTeamId_935:{SCTeamId:3782,SCTeamName:"Saint-Étienne",IMTeamName:"AS Saint Etienne"},
	IMTeamId_936:{SCTeamId:3777,SCTeamName:"Metz",IMTeamName:"FC Metz"},
	IMTeamId_937:{SCTeamId:3792,SCTeamName:"Nancy",IMTeamName:"AS Nancy Lorraine"},
	IMTeamId_939:{SCTeamId:3788,SCTeamName:"Lorient",IMTeamName:"FC Lorient"},
	IMTeamId_940:{SCTeamId:3778,SCTeamName:"Bastia",IMTeamName:"SC Bastia"},
	IMTeamId_941:{SCTeamId:3774,SCTeamName:"Rennes",IMTeamName:"Stade Rennais FC"},
	IMTeamId_942:{SCTeamId:3787,SCTeamName:"Montpellier",IMTeamName:"Montpellier HSC"},
	IMTeamId_943:{SCTeamId:3776,SCTeamName:"Lille",IMTeamName:"Lille OSC"},
	IMTeamId_946:{SCTeamId:12300,SCTeamName:"Cobresal",IMTeamName:"Cobresal"},
	IMTeamId_947:{SCTeamId:12286,SCTeamName:"Huachipato",IMTeamName:"CD Huachipato"},
	IMTeamId_950:{SCTeamId:8151,SCTeamName:"Longford Town",IMTeamName:"Longford Town FC"},
	IMTeamId_952:{SCTeamId:13559,SCTeamName:"Lechia Gdańsk",IMTeamName:"Lechia Gdansk"},
	IMTeamId_954:{SCTeamId:689,SCTeamName:"Real Zaragoza",IMTeamName:"Real Zaragoza"},
	IMTeamId_957:{SCTeamId:3185,SCTeamName:"Torino",IMTeamName:"Torino"},
	IMTeamId_958:{SCTeamId:3164,SCTeamName:"Sampdoria",IMTeamName:"Sampdoria"},
	IMTeamId_960:{SCTeamId:12064,SCTeamName:"Newell's Old Boys",IMTeamName:"CA Newells Old Boys"},
	IMTeamId_961:{SCTeamId:12061,SCTeamName:"Gimnasia La Plata",IMTeamName:"Gimnasia La Plata"},
	IMTeamId_963:{SCTeamId:15015,SCTeamName:"Vancouver Whitecaps",IMTeamName:"Vancouver Whitecaps FC"},
	IMTeamId_964:{SCTeamId:12095,SCTeamName:"Sarmiento",IMTeamName:"Sarmiento De Junin"},
	IMTeamId_965:{SCTeamId:9606,SCTeamName:"Porto",IMTeamName:"FC Porto"},
	IMTeamId_966:{SCTeamId:8068,SCTeamName:"Orlando City",IMTeamName:"Orlando City SC"},
	IMTeamId_967:{SCTeamId:7853,SCTeamName:"Colorado Rapids",IMTeamName:"Colorado Rapids"},
	IMTeamId_968:{SCTeamId:12284,SCTeamName:"Santiago Wanderers",IMTeamName:"Santiago Wanderers"},
	IMTeamId_969:{SCTeamId:12056,SCTeamName:"Banfield",IMTeamName:"Club Atletico Banfield"},
	IMTeamId_971:{SCTeamId:12068,SCTeamName:"Racing Club",IMTeamName:"Racing Club"},
	IMTeamId_972:{SCTeamId:12290,SCTeamName:"Unión Española",IMTeamName:"Union Espanola"},
	IMTeamId_974:{SCTeamId:12093,SCTeamName:"Unión Santa Fe",IMTeamName:"Union De Santa Fe"},
	IMTeamId_975:{SCTeamId:7855,SCTeamName:"Columbus Crew",IMTeamName:"Columbus Crew"},
	IMTeamId_976:{SCTeamId:32556,SCTeamName:"New York City",IMTeamName:"New York City FC"},
	IMTeamId_977:{SCTeamId:7945,SCTeamName:"New York RB",IMTeamName:"New York Red Bulls"},
	IMTeamId_978:{SCTeamId:7848,SCTeamName:"Chicago Fire",IMTeamName:"Chicago Fire"},
	IMTeamId_979:{SCTeamId:7869,SCTeamName:"Dallas",IMTeamName:"FC Dallas"},
	IMTeamId_980:{SCTeamId:8095,SCTeamName:"Minnesota United",IMTeamName:"Minnesota United FC"},
	IMTeamId_981:{SCTeamId:8113,SCTeamName:"Portland Timbers",IMTeamName:"Portland Timbers"},
	IMTeamId_982:{SCTeamId:7851,SCTeamName:"SJ Earthquakes",IMTeamName:"San Jose Earthquakes"},
	IMTeamId_983:{SCTeamId:7849,SCTeamName:"Sporting KC",IMTeamName:"Sporting Kansas City"},
	IMTeamId_984:{SCTeamId:7871,SCTeamName:"Real Salt Lake",IMTeamName:"Real Salt Lake"},
	IMTeamId_985:{SCTeamId:8067,SCTeamName:"Seattle Sounders",IMTeamName:"Seattle Sounders"},
	IMTeamId_986:{SCTeamId:7847,SCTeamName:"Los Angeles Galaxy",IMTeamName:"Los Angeles Galaxy"},
	IMTeamId_987:{SCTeamId:7854,SCTeamName:"New England",IMTeamName:"New England Revolution"},
	IMTeamId_988:{SCTeamId:8061,SCTeamName:"Philadelphia Union",IMTeamName:"Philadelphia Union"},
	IMTeamId_989:{SCTeamId:12805,SCTeamName:"Shimizu S-Pulse",IMTeamName:"Shimizu S-Pulse"},
	IMTeamId_992:{SCTeamId:12807,SCTeamName:"Kashiwa Reysol",IMTeamName:"Kashiwa Reysol"},
	IMTeamId_993:{SCTeamId:12806,SCTeamName:"Tokyo",IMTeamName:"FC Tokyo"},
	IMTeamId_994:{SCTeamId:12810,SCTeamName:"Sanfrecce Hiroshima",IMTeamName:"Hiroshima Sanfrecce"},
	IMTeamId_996:{SCTeamId:12823,SCTeamName:"Consadole Sapporo",IMTeamName:"Consadole Sapporo"},
	IMTeamId_1002:{SCTeamId:12819,SCTeamName:"Sagan Tosu",IMTeamName:"Sagan Tosu"},
	IMTeamId_1003:{SCTeamId:12804,SCTeamName:"Vissel Kobe",IMTeamName:"Vissel Kobe"},
	IMTeamId_1005:{SCTeamId:12798,SCTeamName:"Yokohama F. Marinos",IMTeamName:"Yokohama Marinos"},
	IMTeamId_1006:{SCTeamId:681,SCTeamName:"Osasuna",IMTeamName:"CA Osasuna"},
	IMTeamId_1009:{SCTeamId:12811,SCTeamName:"Cerezo Osaka",IMTeamName:"Cerezo Osaka"},
	IMTeamId_1010:{SCTeamId:741,SCTeamName:"Alcorcón",IMTeamName:"AD Alcorcon"},
	IMTeamId_1011:{SCTeamId:700,SCTeamName:"Cádiz",IMTeamName:"Cadiz CF"},
	IMTeamId_1015:{SCTeamId:1748,SCTeamName:"AFC Wimbledon",IMTeamName:"AFC Wimbledon"},
	IMTeamId_1016:{SCTeamId:1665,SCTeamName:"Oldham Athletic",IMTeamName:"Oldham Athletic"},
	IMTeamId_1017:{SCTeamId:1685,SCTeamName:"Bristol Rovers",IMTeamName:"Bristol Rovers"},
	IMTeamId_1018:{SCTeamId:1638,SCTeamName:"Millwall",IMTeamName:"Millwall"},
	IMTeamId_1019:{SCTeamId:1693,SCTeamName:"Rochdale",IMTeamName:"Rochdale AFC"},
	IMTeamId_1020:{SCTeamId:1653,SCTeamName:"Bradford City",IMTeamName:"Bradford City"},
	IMTeamId_1021:{SCTeamId:1617,SCTeamName:"Charlton Athletic",IMTeamName:"Charlton Athletic"},
	IMTeamId_1022:{SCTeamId:1656,SCTeamName:"Swindon Town",IMTeamName:"Swindon Town"},
	IMTeamId_1023:{SCTeamId:1615,SCTeamName:"Bolton Wanderers",IMTeamName:"Bolton Wanderers"},
	IMTeamId_1029:{SCTeamId:1654,SCTeamName:"Milton Keynes Dons",IMTeamName:"Milton Keynes Dons"},
	IMTeamId_1030:{SCTeamId:1636,SCTeamName:"Sheffield United",IMTeamName:"Sheffield United"},
	IMTeamId_1031:{SCTeamId:1681,SCTeamName:"Northampton Town",IMTeamName:"Northampton Town"},
	IMTeamId_1032:{SCTeamId:1670,SCTeamName:"Chesterfield",IMTeamName:"Chesterfield"},
	IMTeamId_1033:{SCTeamId:1648,SCTeamName:"Gillingham",IMTeamName:"Gillingham FC"},
	IMTeamId_1034:{SCTeamId:1687,SCTeamName:"Southend United",IMTeamName:"Southend United"},
	IMTeamId_1036:{SCTeamId:1683,SCTeamName:"Oxford United",IMTeamName:"Oxford United"},
	IMTeamId_1037:{SCTeamId:1697,SCTeamName:"Shrewsbury Town",IMTeamName:"Shrewsbury Town"},
	IMTeamId_1038:{SCTeamId:10531,SCTeamName:"Swansea City",IMTeamName:"Swansea City"},
	IMTeamId_1039:{SCTeamId:7456,SCTeamName:"Viborg",IMTeamName:"Viborg FF"},
	IMTeamId_1040:{SCTeamId:2468,SCTeamName:"Erzgebirge Aue",IMTeamName:"Erzgebirge Aue"},
	IMTeamId_1042:{SCTeamId:2455,SCTeamName:"Hannover 96",IMTeamName:"Hannover 96"},
	IMTeamId_1044:{SCTeamId:2502,SCTeamName:"Fortuna Düsseldorf",IMTeamName:"Fortuna Dusseldorf"},
	IMTeamId_1049:{SCTeamId:6410,SCTeamName:"St. Gallen",IMTeamName:"FC St Gallen"},
	IMTeamId_1050:{SCTeamId:6408,SCTeamName:"Young Boys",IMTeamName:"BSC Young Boys"},
	IMTeamId_1051:{SCTeamId:6413,SCTeamName:"Thun",IMTeamName:"FC Thun"},
	IMTeamId_1053:{SCTeamId:7615,SCTeamName:"HB Køge",IMTeamName:"HB Koge"},
	IMTeamId_1054:{SCTeamId:7526,SCTeamName:"Nykøbing",IMTeamName:"Nykobing FC"},
	IMTeamId_1057:{SCTeamId:7473,SCTeamName:"Vejle",IMTeamName:"Vejle BK"},
	IMTeamId_1058:{SCTeamId:7469,SCTeamName:"Fredericia",IMTeamName:"FC Fredericia"},
	IMTeamId_1060:{SCTeamId:7566,SCTeamName:"Helsingør",IMTeamName:"FC Helsingor"},
	IMTeamId_1062:{SCTeamId:7510,SCTeamName:"Hobro",IMTeamName:"Hobro IK"},
	IMTeamId_1066:{SCTeamId:7213,SCTeamName:"Mjøndalen",IMTeamName:"Mjondalen IF"},
	IMTeamId_1070:{SCTeamId:4793,SCTeamName:"Mariehamn",IMTeamName:"IFK Mariehamn"},
	IMTeamId_1071:{SCTeamId:4792,SCTeamName:"VPS",IMTeamName:"VPS Vaasa"},
	IMTeamId_1072:{SCTeamId:3193,SCTeamName:"Genoa",IMTeamName:"Genoa"},
	IMTeamId_1074:{SCTeamId:3173,SCTeamName:"Cagliari",IMTeamName:"Cagliari"},
	IMTeamId_1075:{SCTeamId:3197,SCTeamName:"Crotone",IMTeamName:"Crotone"},
	IMTeamId_1076:{SCTeamId:3157,SCTeamName:"Milan",IMTeamName:"AC Milan"},
	IMTeamId_1079:{SCTeamId:3176,SCTeamName:"Fiorentina",IMTeamName:"Fiorentina"},
	IMTeamId_1080:{SCTeamId:3178,SCTeamName:"Empoli",IMTeamName:"Empoli"},
	IMTeamId_1082:{SCTeamId:3166,SCTeamName:"Bologna",IMTeamName:"Bologna"},
	IMTeamId_1083:{SCTeamId:3163,SCTeamName:"Udinese",IMTeamName:"Udinese"},
	IMTeamId_1084:{SCTeamId:4487,SCTeamName:"Fenerbahçe",IMTeamName:"Fenerbahce SK"},
	IMTeamId_1085:{SCTeamId:4499,SCTeamName:"Rizespor",IMTeamName:"Caykur Rizespor"},
	IMTeamId_1086:{SCTeamId:3783,SCTeamName:"Caen",IMTeamName:"SM Caen CBN"},
	IMTeamId_1088:{SCTeamId:3771,SCTeamName:"Olympique Marseille",IMTeamName:"Olympique de Marseille"},
	IMTeamId_1089:{SCTeamId:1623,SCTeamName:"Everton",IMTeamName:"Everton"},
	IMTeamId_1092:{SCTeamId:1620,SCTeamName:"Middlesbrough",IMTeamName:"Middlesbrough"},
	IMTeamId_1093:{SCTeamId:2481,SCTeamName:"Augsburg",IMTeamName:"FC Augsburg"},
	IMTeamId_1095:{SCTeamId:13527,SCTeamName:"Jagiellonia Białystok",IMTeamName:"Jagiellonia Bialystok"},
	IMTeamId_1096:{SCTeamId:13518,SCTeamName:"Pogoń Szczecin",IMTeamName:"Pogon Szczecin"},
	IMTeamId_1097:{SCTeamId:6411,SCTeamName:"Grasshopper",IMTeamName:"Grasshopper Club Zurich"},
	IMTeamId_1098:{SCTeamId:6433,SCTeamName:"Lugano",IMTeamName:"FC Lugano"},
	IMTeamId_1099:{SCTeamId:847,SCTeamName:"Lugo",IMTeamName:"CD Lugo"},
	IMTeamId_1100:{SCTeamId:756,SCTeamName:"Girona",IMTeamName:"Girona"},
	IMTeamId_1101:{SCTeamId:9684,SCTeamName:"Porto II",IMTeamName:"FC Porto B"},
	IMTeamId_1103:{SCTeamId:7484,SCTeamName:"Lyngby",IMTeamName:"Lyngby BK"},
	IMTeamId_1104:{SCTeamId:8869,SCTeamName:"Admira",IMTeamName:"Admira Wacker Modling"},
	IMTeamId_1105:{SCTeamId:8738,SCTeamName:"Rapid Wien",IMTeamName:"SK Rapid Wien"},
	IMTeamId_1107:{SCTeamId:6897,SCTeamName:"Varberg",IMTeamName:"Varbergs BoIS"},
	IMTeamId_1108:{SCTeamId:12302,SCTeamName:"O'Higgins",IMTeamName:"O Higgins FC"},
	IMTeamId_1110:{SCTeamId:3804,SCTeamName:"Dijon",IMTeamName:"Dijon FCO"},
	IMTeamId_1111:{SCTeamId:3772,SCTeamName:"Bordeaux",IMTeamName:"FC Girondins de Bordeaux"},
	IMTeamId_1112:{SCTeamId:11311,SCTeamName:"Karviná",IMTeamName:"MFK Karvina"},
	IMTeamId_1114:{SCTeamId:11267,SCTeamName:"Hradec Králové",IMTeamName:"FC Hradec Kralove"},
	IMTeamId_1115:{SCTeamId:9789,SCTeamName:"Arouca",IMTeamName:"FC Arouca"},
	IMTeamId_1116:{SCTeamId:9633,SCTeamName:"Feirense",IMTeamName:"CD Feirense"},
	IMTeamId_1117:{SCTeamId:9612,SCTeamName:"Marítimo",IMTeamName:"CS Maritimo"},
	IMTeamId_1119:{SCTeamId:9625,SCTeamName:"Penafiel",IMTeamName:"FC Penafiel"},
	IMTeamId_1120:{SCTeamId:9634,SCTeamName:"Santa Clara",IMTeamName:"CD Santa Clara"},
	IMTeamId_1121:{SCTeamId:9640,SCTeamName:"Sporting Covilhã",IMTeamName:"Sporting Clube Da Covilha"},
	IMTeamId_1123:{SCTeamId:9700,SCTeamName:"Gil Vicente",IMTeamName:"Gil Vicente"},
	IMTeamId_1126:{SCTeamId:9683,SCTeamName:"Vizela",IMTeamName:"Vizela"},
	IMTeamId_1129:{SCTeamId:9665,SCTeamName:"Academico Viseu",IMTeamName:"Academico Viseu(N)"},
	IMTeamId_1130:{SCTeamId:9626,SCTeamName:"Varzim",IMTeamName:"Varzim"},
	IMTeamId_1131:{SCTeamId:2482,SCTeamName:"Hoffenheim",IMTeamName:"TSG 1899 Hoffenheim"},
	IMTeamId_1134:{SCTeamId:11249,SCTeamName:"Jablonec",IMTeamName:"FK Jablonec"},
	IMTeamId_1135:{SCTeamId:4511,SCTeamName:"Antalyaspor",IMTeamName:"Antalyaspor"},
	IMTeamId_1137:{SCTeamId:13505,SCTeamName:"Legia Warszawa",IMTeamName:"Legia Warszawa"},
	IMTeamId_1139:{SCTeamId:7348,SCTeamName:"Jerv",IMTeamName:"FK Jerv"},
	IMTeamId_1141:{SCTeamId:7193,SCTeamName:"Ranheim",IMTeamName:"Ranheim"},
	IMTeamId_1142:{SCTeamId:7124,SCTeamName:"Åsane",IMTeamName:"Asane Fotball"},
	IMTeamId_1144:{SCTeamId:999,SCTeamName:"Mirandés",IMTeamName:"Mirandes"},
	IMTeamId_1145:{SCTeamId:7186,SCTeamName:"Strømmen",IMTeamName:"Strommen IF"},
	IMTeamId_1147:{SCTeamId:7106,SCTeamName:"Aalesund",IMTeamName:"Aalesund FK"},
	IMTeamId_1148:{SCTeamId:7089,SCTeamName:"Tromsø",IMTeamName:"Tromso IL"},
	IMTeamId_1149:{SCTeamId:7187,SCTeamName:"Ullensaker / Kisa",IMTeamName:"Ullensaker Kisa IL"},
	IMTeamId_1150:{SCTeamId:7121,SCTeamName:"Fredrikstad",IMTeamName:"Fredrikstad FK"},
	IMTeamId_1151:{SCTeamId:7190,SCTeamName:"Kristiansund",IMTeamName:"Kristiansund BK"},
	IMTeamId_1152:{SCTeamId:7111,SCTeamName:"Strømsgodset",IMTeamName:"Stromsgodset IF"},
	IMTeamId_1153:{SCTeamId:7205,SCTeamName:"Sandnes Ulf",IMTeamName:"Sandnes Ulf"},
	IMTeamId_1155:{SCTeamId:7105,SCTeamName:"Sandefjord",IMTeamName:"Sandefjord"},
	IMTeamId_1157:{SCTeamId:7097,SCTeamName:"Stabæk",IMTeamName:"Stabaek"},
	IMTeamId_1158:{SCTeamId:7101,SCTeamName:"Sogndal",IMTeamName:"Sogndal"},
	IMTeamId_1159:{SCTeamId:7096,SCTeamName:"Lillestrøm",IMTeamName:"Lillestrom SK"},
	IMTeamId_1162:{SCTeamId:712,SCTeamName:"Leganés",IMTeamName:"CD Leganes"},
	IMTeamId_1163:{SCTeamId:9610,SCTeamName:"Sporting Braga",IMTeamName:"Sporting Clube de Braga"},
	IMTeamId_1166:{SCTeamId:11611,SCTeamName:"CFR Cluj",IMTeamName:"CFR Cluj"},
	IMTeamId_1169:{SCTeamId:7090,SCTeamName:"Odds",IMTeamName:"Odd BK"},
	IMTeamId_1170:{SCTeamId:7092,SCTeamName:"Vålerenga",IMTeamName:"Valerenga"},
	IMTeamId_1171:{SCTeamId:12307,SCTeamName:"Antofagasta",IMTeamName:"CD Antofagasta"},
	IMTeamId_1172:{SCTeamId:12292,SCTeamName:"Audax Italiano",IMTeamName:"Audax Italiano"},
	IMTeamId_1173:{SCTeamId:3161,SCTeamName:"Internazionale",IMTeamName:"Inter Milan"},
	IMTeamId_1174:{SCTeamId:3187,SCTeamName:"Napoli",IMTeamName:"Napoli"},
	IMTeamId_1176:{SCTeamId:58165,SCTeamName:"Atlanta United",IMTeamName:"Atlanta United FC"},
	IMTeamId_1178:{SCTeamId:3775,SCTeamName:"Nice",IMTeamName:"OGC Nice"},
	IMTeamId_1179:{SCTeamId:3767,SCTeamName:"PSG",IMTeamName:"Paris Saint Germain"},
	IMTeamId_1180:{SCTeamId:9620,SCTeamName:"Belenenses",IMTeamName:"Belenenses"},
	IMTeamId_1181:{SCTeamId:9621,SCTeamName:"Paços de Ferreira",IMTeamName:"Pacos de Ferreira"},
	IMTeamId_1182:{SCTeamId:12070,SCTeamName:"Rosario Central",IMTeamName:"CA Rosario Central"},
	IMTeamId_1183:{SCTeamId:12096,SCTeamName:"Aldosivi",IMTeamName:"Club Atletico Aldosivi"},
	IMTeamId_1184:{SCTeamId:12288,SCTeamName:"Colo Colo",IMTeamName:"Colo Colo"},
	IMTeamId_1186:{SCTeamId:12299,SCTeamName:"Palestino",IMTeamName:"CD Palestino"},
	IMTeamId_1187:{SCTeamId:6764,SCTeamName:"Norrby",IMTeamName:"Norrby IF"},
	IMTeamId_1189:{SCTeamId:6728,SCTeamName:"Östers",IMTeamName:"Osters IF"},
	IMTeamId_1191:{SCTeamId:6718,SCTeamName:"Helsingborg",IMTeamName:"Helsingborgs IF"},
	IMTeamId_1192:{SCTeamId:6741,SCTeamName:"Degerfors",IMTeamName:"Degerfors IF"},
	IMTeamId_1193:{SCTeamId:802,SCTeamName:"Huesca",IMTeamName:"SD Huesca"},
	IMTeamId_1194:{SCTeamId:713,SCTeamName:"Rayo Vallecano",IMTeamName:"Rayo Vallecano"},
	IMTeamId_1195:{SCTeamId:11246,SCTeamName:"Slovan Liberec",IMTeamName:"FC Slovan Liberec"},
	IMTeamId_1197:{SCTeamId:13520,SCTeamName:"Zagłębie Lubin",IMTeamName:"Zaglebie Lubin"},
	IMTeamId_1198:{SCTeamId:13521,SCTeamName:"Cracovia Kraków",IMTeamName:"Cracovia Krakow"},
	IMTeamId_1201:{SCTeamId:4492,SCTeamName:"Galatasaray",IMTeamName:"Galatasaray SK"},
	IMTeamId_1205:{SCTeamId:7136,SCTeamName:"Sarpsborg 08",IMTeamName:"Sarpsborg 08"},
	IMTeamId_1206:{SCTeamId:7091,SCTeamName:"Rosenborg",IMTeamName:"Rosenborg BK"},
	IMTeamId_1207:{SCTeamId:7461,SCTeamName:"Silkeborg",IMTeamName:"Silkeborg IF"},
	IMTeamId_1209:{SCTeamId:1644,SCTeamName:"Watford",IMTeamName:"Watford"},
	IMTeamId_1210:{SCTeamId:1612,SCTeamName:"Liverpool",IMTeamName:"Liverpool"},
	IMTeamId_1211:{SCTeamId:6769,SCTeamName:"Värnamo",IMTeamName:"IFK Varnamo"},
	IMTeamId_1212:{SCTeamId:7099,SCTeamName:"Bodø / Glimt",IMTeamName:"Bodo Glimt"},
	IMTeamId_1213:{SCTeamId:7102,SCTeamName:"Start",IMTeamName:"IK Start"},
	IMTeamId_1214:{SCTeamId:9,SCTeamName:"Ajax",IMTeamName:"Ajax"},
	IMTeamId_1222:{SCTeamId:12381,SCTeamName:"Chile",IMTeamName:"Chile"},
	IMTeamId_1224:{SCTeamId:3148,SCTeamName:"Germany",IMTeamName:"Germany"},
	IMTeamId_1228:{SCTeamId:5677,SCTeamName:"Bahia",IMTeamName:"Esporte Clube Bahia"},
	IMTeamId_1231:{SCTeamId:30286,SCTeamName:"Mineros de Zacatecas",IMTeamName:"Mineros De Zacatecas"},
	IMTeamId_1664:{SCTeamId:20,SCTeamName:"RKC Waalwijk",IMTeamName:"RKC Waalwijk"},
	IMTeamId_1665:{SCTeamId:44,SCTeamName:"Fortuna Sittard",IMTeamName:"Fortuna Sittard"},
	IMTeamId_1670:{SCTeamId:25,SCTeamName:"Volendam",IMTeamName:"FC Volendam"},
	IMTeamId_1671:{SCTeamId:43,SCTeamName:"MVV",IMTeamName:"MVV Maastricht"},
	IMTeamId_1672:{SCTeamId:31,SCTeamName:"De Graafschap",IMTeamName:"De Graafschap"},
	IMTeamId_1674:{SCTeamId:28,SCTeamName:"Helmond Sport",IMTeamName:"Helmond Sport"},
	IMTeamId_1675:{SCTeamId:47,SCTeamName:"Almere City",IMTeamName:"Almere City FC"},
	IMTeamId_1678:{SCTeamId:41,SCTeamName:"Dordrecht",IMTeamName:"FC Dordrecht"},
	IMTeamId_1679:{SCTeamId:33,SCTeamName:"Emmen",IMTeamName:"FC Emmen"},
	IMTeamId_1680:{SCTeamId:160,SCTeamName:"PSV II",IMTeamName:"Jong PSV Eindhoven"},
	IMTeamId_1681:{SCTeamId:37,SCTeamName:"Telstar",IMTeamName:"Telstar"},
	IMTeamId_1682:{SCTeamId:40,SCTeamName:"Cambuur",IMTeamName:"SC Cambuur"},
	IMTeamId_1684:{SCTeamId:32,SCTeamName:"VVV Venlo",IMTeamName:"VVV Venlo"},
	IMTeamId_1685:{SCTeamId:152,SCTeamName:"Ajax II",IMTeamName:"Jong Ajax"},
	IMTeamId_1686:{SCTeamId:5070,SCTeamName:"Cercle Brugge",IMTeamName:"Cercle Brugge"},
	IMTeamId_1688:{SCTeamId:5121,SCTeamName:"OH Leuven",IMTeamName:"Oud - Heverlee Leuven"},
	IMTeamId_1697:{SCTeamId:15444,SCTeamName:"Monterrey",IMTeamName:"Monterrey Rayados"},
	IMTeamId_1732:{SCTeamId:5081,SCTeamName:"Genk",IMTeamName:"KRC Genk"},
	IMTeamId_1740:{SCTeamId:5100,SCTeamName:"Eupen",IMTeamName:"KAS Eupen"},
	IMTeamId_1751:{SCTeamId:5110,SCTeamName:"Mechelen",IMTeamName:"KV Mechelen"},
	IMTeamId_1760:{SCTeamId:6710,SCTeamName:"Hammarby",IMTeamName:"Hammarby IF"},
	IMTeamId_1761:{SCTeamId:6770,SCTeamName:"Eskilstuna",IMTeamName:"AFC Eskilstuna"},
	IMTeamId_1778:{SCTeamId:10,SCTeamName:"AZ",IMTeamName:"AZ Alkmaar"},
	IMTeamId_1779:{SCTeamId:24,SCTeamName:"Vitesse",IMTeamName:"Vitesse"},
	IMTeamId_1787:{SCTeamId:6720,SCTeamName:"GIF Sundsvall",IMTeamName:"GIF Sundsvall"},
	IMTeamId_1805:{SCTeamId:12054,SCTeamName:"Arsenal",IMTeamName:"Arsenal de Sarandi"},
	IMTeamId_1808:{SCTeamId:6719,SCTeamName:"Örebro",IMTeamName:"Orebro SK"},
	IMTeamId_1809:{SCTeamId:3801,SCTeamName:"Laval",IMTeamName:"Stade Lavallois"},
	IMTeamId_1810:{SCTeamId:6736,SCTeamName:"Häcken",IMTeamName:"BK Hacken"},
	IMTeamId_1811:{SCTeamId:6712,SCTeamName:"IFK Göteborg",IMTeamName:"IFK Goteborg"},
	IMTeamId_1812:{SCTeamId:6721,SCTeamName:"Elfsborg",IMTeamName:"IF Elfsborg"},
	IMTeamId_1813:{SCTeamId:6788,SCTeamName:"Östersunds FK",IMTeamName:"Ostersunds"},
	IMTeamId_1817:{SCTeamId:1598,SCTeamName:"Spain",IMTeamName:"Spain"},
	IMTeamId_1818:{SCTeamId:4418,SCTeamName:"France",IMTeamName:"France"},
	IMTeamId_1819:{SCTeamId:3757,SCTeamName:"Italy",IMTeamName:"Italy"},
	IMTeamId_2326:{SCTeamId:1702,SCTeamName:"Aldershot Town",IMTeamName:"Aldershot Town"},
	IMTeamId_2331:{SCTeamId:12926,SCTeamName:"Flora",IMTeamName:"FC Flora Tallinn"},
	IMTeamId_2336:{SCTeamId:1749,SCTeamName:"Barrow",IMTeamName:"Barrow AFC"},
	IMTeamId_2344:{SCTeamId:1709,SCTeamName:"Dagenham & Redbridge",IMTeamName:"Dagenham And Redbridge"},
	IMTeamId_2345:{SCTeamId:1706,SCTeamName:"Woking",IMTeamName:"Woking"},
	IMTeamId_2346:{SCTeamId:1772,SCTeamName:"Eastleigh",IMTeamName:"Eastleigh FC"},
	IMTeamId_2352:{SCTeamId:6430,SCTeamName:"Winterthur",IMTeamName:"FC Winterthur"},
	IMTeamId_2353:{SCTeamId:6414,SCTeamName:"Aarau",IMTeamName:"FC Aarau"},
	IMTeamId_2362:{SCTeamId:6417,SCTeamName:"FC Schaffhausen",IMTeamName:"FC Schaffhausen"},
	IMTeamId_2363:{SCTeamId:6409,SCTeamName:"Servette",IMTeamName:"Servette FC"},
	IMTeamId_2365:{SCTeamId:1820,SCTeamName:"Bromley",IMTeamName:"Bromley FC"},
	IMTeamId_2367:{SCTeamId:2015,SCTeamName:"Solihull Moors",IMTeamName:"Solihull Moors FC"},
	IMTeamId_2369:{SCTeamId:1766,SCTeamName:"Sutton United",IMTeamName:"Sutton United FC"},
	IMTeamId_2370:{SCTeamId:1661,SCTeamName:"Tranmere Rovers",IMTeamName:"Tranmere Rovers"},
	IMTeamId_2372:{SCTeamId:1674,SCTeamName:"Torquay United",IMTeamName:"Torquay United"},
	IMTeamId_2377:{SCTeamId:1713,SCTeamName:"Forest Green Rovers",IMTeamName:"Forest Green Rovers"},
	IMTeamId_2393:{SCTeamId:12075,SCTeamName:"Argentinos Juniors",IMTeamName:"Argentinos Juniors"},
	IMTeamId_2410:{SCTeamId:4802,SCTeamName:"Klubi-04",IMTeamName:"Klubi 04"},
	IMTeamId_2417:{SCTeamId:6416,SCTeamName:"Wil",IMTeamName:"FC Wil 1900"},
	IMTeamId_2428:{SCTeamId:11243,SCTeamName:"Sigma Olomouc",IMTeamName:"SK Sigma Olomouc"},
	IMTeamId_2455:{SCTeamId:15415,SCTeamName:"Santos Laguna",IMTeamName:"Santos Laguna"},
	IMTeamId_2457:{SCTeamId:15407,SCTeamName:"Atlas",IMTeamName:"Atlas"},
	IMTeamId_2458:{SCTeamId:15413,SCTeamName:"Pachuca",IMTeamName:"Pachuca"},
	IMTeamId_2459:{SCTeamId:15408,SCTeamName:"Cruz Azul",IMTeamName:"Cruz Azul"},
	IMTeamId_2461:{SCTeamId:15420,SCTeamName:"Pumas UNAM",IMTeamName:"Pumas UNAM"},
	IMTeamId_2462:{SCTeamId:15417,SCTeamName:"Tigres UANL",IMTeamName:"Tigres UANL"},
	IMTeamId_2463:{SCTeamId:15459,SCTeamName:"Club Tijuana",IMTeamName:"Club Tijuana"},
	IMTeamId_2464:{SCTeamId:15409,SCTeamName:"Guadalajara",IMTeamName:"CD Guadalajara Chivas"},
	IMTeamId_2465:{SCTeamId:15424,SCTeamName:"León",IMTeamName:"Club Leon"},
	IMTeamId_2501:{SCTeamId:16336,SCTeamName:"Golden Arrows",IMTeamName:"Golden Arrows FC"},
	IMTeamId_2502:{SCTeamId:16344,SCTeamName:"Mamelodi Sundowns",IMTeamName:"Mamelodi Sundowns FC"},
	IMTeamId_2574:{SCTeamId:6727,SCTeamName:"Västerås SK",IMTeamName:"Vasteras SK"},
	IMTeamId_2579:{SCTeamId:15418,SCTeamName:"Toluca",IMTeamName:"Deportivo Toluca"},
	IMTeamId_2580:{SCTeamId:15421,SCTeamName:"Querétaro",IMTeamName:"Queretaro FC"},
	IMTeamId_2581:{SCTeamId:15414,SCTeamName:"Puebla",IMTeamName:"Puebla FC"},
	IMTeamId_2582:{SCTeamId:15412,SCTeamName:"Necaxa",IMTeamName:"Club Necaxa"},
	IMTeamId_2586:{SCTeamId:6723,SCTeamName:"Brage",IMTeamName:"IK Brage"},
	IMTeamId_2602:{SCTeamId:6781,SCTeamName:"Vasalund",IMTeamName:"Vasalunds IF"},
	IMTeamId_2604:{SCTeamId:6913,SCTeamName:"Akropolis",IMTeamName:"Akropolis IF"},
	IMTeamId_2684:{SCTeamId:6717,SCTeamName:"Landskrona",IMTeamName:"Landskrona BoIS"},
	IMTeamId_2708:{SCTeamId:743,SCTeamName:"Fuenlabrada",IMTeamName:"CF Fuenlabrada"},
	IMTeamId_2716:{SCTeamId:926,SCTeamName:"Amorebieta",IMTeamName:"SD Amorebieta"},
	IMTeamId_2857:{SCTeamId:8528,SCTeamName:"Ayr United",IMTeamName:"Ayr United FC"},
	IMTeamId_2858:{SCTeamId:8514,SCTeamName:"Hibernian",IMTeamName:"Hibernian FC"},
	IMTeamId_2867:{SCTeamId:8511,SCTeamName:"Dunfermline Athletic",IMTeamName:"Dunfermline Athletic FC"},
	IMTeamId_2868:{SCTeamId:8531,SCTeamName:"Greenock Morton",IMTeamName:"Greenock Morton FC"},
	IMTeamId_2870:{SCTeamId:8525,SCTeamName:"Queen of the South",IMTeamName:"Queen of the South FC"},
	IMTeamId_2874:{SCTeamId:8513,SCTeamName:"Dundee United",IMTeamName:"Dundee United FC"},
	IMTeamId_2877:{SCTeamId:8527,SCTeamName:"Raith Rovers",IMTeamName:"Raith Rovers FC"},
	IMTeamId_2880:{SCTeamId:1714,SCTeamName:"Halifax Town",IMTeamName:"Halifax Town"},
	IMTeamId_2897:{SCTeamId:8515,SCTeamName:"Livingston",IMTeamName:"Livingston FC"},
	IMTeamId_2899:{SCTeamId:2071,SCTeamName:"Salford City",IMTeamName:"Salford City"},
	IMTeamId_2923:{SCTeamId:1667,SCTeamName:"Stockport County",IMTeamName:"Stockport County"},
	IMTeamId_2926:{SCTeamId:1745,SCTeamName:"Altrincham",IMTeamName:"Altrincham"},
	IMTeamId_2959:{SCTeamId:8536,SCTeamName:"Arbroath",IMTeamName:"Arbroath FC"},
	IMTeamId_2982:{SCTeamId:37894,SCTeamName:"San Antonio",IMTeamName:"San Antonio FC"},
	IMTeamId_3030:{SCTeamId:1769,SCTeamName:"Maidenhead United",IMTeamName:"Maidenhead United"},
	IMTeamId_3121:{SCTeamId:3200,SCTeamName:"Como",IMTeamName:"Como"},
	IMTeamId_3147:{SCTeamId:3244,SCTeamName:"Alessandria",IMTeamName:"Alessandria Calcio"},
	IMTeamId_3149:{SCTeamId:3235,SCTeamName:"Cremonese",IMTeamName:"US Cremonese"},
	IMTeamId_3228:{SCTeamId:12314,SCTeamName:"Unión La Calera",IMTeamName:"Union La Calera"},
	IMTeamId_3728:{SCTeamId:5648,SCTeamName:"Fluminense",IMTeamName:"Fluminense Football Club"},
	IMTeamId_3729:{SCTeamId:5654,SCTeamName:"Flamengo",IMTeamName:"Clube de Regatas do Flamengo"},
	IMTeamId_3733:{SCTeamId:5653,SCTeamName:"Atlético Mineiro",IMTeamName:"Clube Atletico Mineiro"},
	IMTeamId_3793:{SCTeamId:5656,SCTeamName:"Corinthians",IMTeamName:"Sport Club Corinthians Paulista"},
	IMTeamId_3848:{SCTeamId:9170,SCTeamName:"Shenzhen",IMTeamName:"Shenzhen FC"},
	IMTeamId_3860:{SCTeamId:5669,SCTeamName:"Ceará",IMTeamName:"Ceara Sporting Club"},
	IMTeamId_3865:{SCTeamId:5644,SCTeamName:"Internacional",IMTeamName:"Sport Club Internacional"},
	IMTeamId_3886:{SCTeamId:5651,SCTeamName:"Athletico Paranaense",IMTeamName:"Clube Atletico Paranaense"},
	IMTeamId_3940:{SCTeamId:5674,SCTeamName:"Sport Recife",IMTeamName:"Sport Club do Recife"},
	IMTeamId_4135:{SCTeamId:11405,SCTeamName:"Pardubice",IMTeamName:"FK Pardubice"},
	IMTeamId_4144:{SCTeamId:11240,SCTeamName:"Baník Ostrava",IMTeamName:"FC Banik Ostrava"},
	IMTeamId_4149:{SCTeamId:11251,SCTeamName:"Opava",IMTeamName:"SFC Opava"},
	IMTeamId_4248:{SCTeamId:1833,SCTeamName:"Wealdstone",IMTeamName:"Wealdstone"},
	IMTeamId_4340:{SCTeamId:10984,SCTeamName:"Kairat",IMTeamName:"FC Kairat Almaty"},
	IMTeamId_4414:{SCTeamId:12442,SCTeamName:"Neftchi",IMTeamName:"Neftchi Baku PFC"},
	IMTeamId_4449:{SCTeamId:21992,SCTeamName:"Alashkert",IMTeamName:"Alashkert FC(N)"},
	IMTeamId_4455:{SCTeamId:15643,SCTeamName:"Fénix",IMTeamName:"Centro Atletico Fenix"},
	IMTeamId_4472:{SCTeamId:10693,SCTeamName:"Anorthosis",IMTeamName:"Anorthosis Famagusta"},
	IMTeamId_4473:{SCTeamId:10690,SCTeamName:"Omonia Nicosia",IMTeamName:"Omonia Nicosia"},
	IMTeamId_4525:{SCTeamId:7093,SCTeamName:"HamKam",IMTeamName:"HamKam"},
	IMTeamId_4528:{SCTeamId:7345,SCTeamName:"Grorud",IMTeamName:"Grorud IL"},
	IMTeamId_4535:{SCTeamId:7116,SCTeamName:"Raufoss",IMTeamName:"Raufoss IL"},
	IMTeamId_4538:{SCTeamId:7239,SCTeamName:"KFUM",IMTeamName:"KFUM Fotball Oslo"},
	IMTeamId_4590:{SCTeamId:16345,SCTeamName:"SuperSport United",IMTeamName:"Supersport United FC"},
	IMTeamId_4591:{SCTeamId:16338,SCTeamName:"Kaizer Chiefs",IMTeamName:"Kaizer Chiefs"},
	IMTeamId_4608:{SCTeamId:16341,SCTeamName:"Orlando Pirates",IMTeamName:"Orlando Pirates FC"},
	IMTeamId_4609:{SCTeamId:16418,SCTeamName:"Chippa United",IMTeamName:"Chippa United FC"},
	IMTeamId_4722:{SCTeamId:5080,SCTeamName:"KV Oostende",IMTeamName:"KV Oostende"},
	IMTeamId_4723:{SCTeamId:5072,SCTeamName:"Club Brugge",IMTeamName:"Club Brugge"},
	IMTeamId_4763:{SCTeamId:4828,SCTeamName:"MuSa",IMTeamName:"Musan Salama"},
	IMTeamId_4835:{SCTeamId:8754,SCTeamName:"LASK Linz",IMTeamName:"LASK Linz"},
	IMTeamId_5194:{SCTeamId:37892,SCTeamName:"Cincinnati",IMTeamName:"FC Cincinnati"},
	IMTeamId_5210:{SCTeamId:32831,SCTeamName:"Charlotte Independence",IMTeamName:"Charlotte Independence"},
	IMTeamId_5213:{SCTeamId:7866,SCTeamName:"Charleston Battery",IMTeamName:"Charleston Battery"},
	IMTeamId_5228:{SCTeamId:3170,SCTeamName:"Reggina",IMTeamName:"Reggina"},
	IMTeamId_5244:{SCTeamId:3168,SCTeamName:"Lecce",IMTeamName:"Lecce"},
	IMTeamId_5291:{SCTeamId:15465,SCTeamName:"Dorados",IMTeamName:"Dorados de Sinaloa"},
	IMTeamId_5292:{SCTeamId:34402,SCTeamName:"Juárez",IMTeamName:"FC Juarez"},
	IMTeamId_5525:{SCTeamId:12079,SCTeamName:"Defensa y Justicia",IMTeamName:"Defensa y Justicia"},
	IMTeamId_5574:{SCTeamId:723,SCTeamName:"Real Sociedad B",IMTeamName:"Real Sociedad B"},
	IMTeamId_5679:{SCTeamId:740,SCTeamName:"Ponferradina",IMTeamName:"Ponferradina"},
	IMTeamId_5687:{SCTeamId:807,SCTeamName:"Cartagena",IMTeamName:"FC Cartagena"},
	IMTeamId_5776:{SCTeamId:12294,SCTeamName:"La Serena",IMTeamName:"Deportes La Serena"},
	IMTeamId_5980:{SCTeamId:9192,SCTeamName:"Dalian Pro",IMTeamName:"Dalian Professional FC"},
	IMTeamId_6245:{SCTeamId:13403,SCTeamName:"Žalgiris",IMTeamName:"Zalgiris Vilnius"},
	IMTeamId_6250:{SCTeamId:12509,SCTeamName:"Olympiacos Piraeus",IMTeamName:"Olympiacos FC"},
	IMTeamId_6332:{SCTeamId:14504,SCTeamName:"Shakhtar Donetsk",IMTeamName:"Shakhtar Donetsk"},
	IMTeamId_6381:{SCTeamId:14536,SCTeamName:"Zorya",IMTeamName:"Zorya Lugansk"},
	IMTeamId_6406:{SCTeamId:17090,SCTeamName:"Crvena Zvezda",IMTeamName:"Crvena Zvezda"},
	IMTeamId_6725:{SCTeamId:7107,SCTeamName:"Bryne",IMTeamName:"Bryne FK"},
	IMTeamId_6727:{SCTeamId:16416,SCTeamName:"Baroka",IMTeamName:"Baroka FC"},
	IMTeamId_7059:{SCTeamId:5707,SCTeamName:"Cuiabá",IMTeamName:"Cuiaba EC"},
	IMTeamId_7454:{SCTeamId:12311,SCTeamName:"Ñublense",IMTeamName:"Nublense"},
	IMTeamId_7769:{SCTeamId:4858,SCTeamName:"KTP",IMTeamName:"FC KTP"},
	IMTeamId_7773:{SCTeamId:4797,SCTeamName:"MP",IMTeamName:"MP Mikkeli"},
	IMTeamId_7860:{SCTeamId:14376,SCTeamName:"Slovan Bratislava",IMTeamName:"Slovan Bratislava"},
	IMTeamId_7976:{SCTeamId:5646,SCTeamName:"Palmeiras",IMTeamName:"Sociedade Esportiva Palmeiras"},
	IMTeamId_8004:{SCTeamId:8832,SCTeamName:"Dornbirn",IMTeamName:"FC Dornbirn 1913"},
	IMTeamId_8265:{SCTeamId:8890,SCTeamName:"Amstetten",IMTeamName:"SKU Amstetten"},
	IMTeamId_8780:{SCTeamId:16367,SCTeamName:"AmaZulu",IMTeamName:"AmaZulu FC"},
	IMTeamId_8792:{SCTeamId:11281,SCTeamName:"Třinec",IMTeamName:"FK Fotbal Trinec"},
	IMTeamId_8858:{SCTeamId:5655,SCTeamName:"Santos",IMTeamName:"Santos SP"},
	IMTeamId_9319:{SCTeamId:11056,SCTeamName:"Sheriff",IMTeamName:"FC Sheriff Tiraspol"},
	IMTeamId_9484:{SCTeamId:38952,SCTeamName:"PK-35 ry",IMTeamName:"PK-35 Vantaa"},
	IMTeamId_9493:{SCTeamId:13515,SCTeamName:"Widzew Łódź",IMTeamName:"Widzew Lodz"},
	IMTeamId_9862:{SCTeamId:4534,SCTeamName:"Hatayspor",IMTeamName:"Hatayspor"},
	IMTeamId_9993:{SCTeamId:34,SCTeamName:"Go Ahead Eagles",IMTeamName:"Go Ahead Eagles"},
	IMTeamId_9994:{SCTeamId:17,SCTeamName:"Utrecht",IMTeamName:"FC Utrecht"},
	IMTeamId_9995:{SCTeamId:22,SCTeamName:"NEC",IMTeamName:"NEC Nijmegen"},
	IMTeamId_9996:{SCTeamId:23,SCTeamName:"PEC Zwolle",IMTeamName:"PEC Zwolle"},
	IMTeamId_9997:{SCTeamId:13,SCTeamName:"Heerenveen",IMTeamName:"SC Heerenveen"},
	IMTeamId_9999:{SCTeamId:15,SCTeamName:"Willem II",IMTeamName:"Willem II"},
	IMTeamId_10000:{SCTeamId:26,SCTeamName:"Excelsior",IMTeamName:"SBV Excelsior"},
	IMTeamId_10001:{SCTeamId:12,SCTeamName:"Feyenoord",IMTeamName:"Feyenoord Rotterdam"},
	IMTeamId_10002:{SCTeamId:29,SCTeamName:"Sparta Rotterdam",IMTeamName:"Sparta Rotterdam"},
	IMTeamId_10003:{SCTeamId:16,SCTeamName:"Twente",IMTeamName:"FC Twente Enschede"},
	IMTeamId_10004:{SCTeamId:21,SCTeamName:"Groningen",IMTeamName:"FC Groningen"},
	IMTeamId_10005:{SCTeamId:11,SCTeamName:"PSV",IMTeamName:"PSV Eindhoven"},
	IMTeamId_10006:{SCTeamId:30,SCTeamName:"Heracles",IMTeamName:"Heracles Almelo"},
	IMTeamId_10502:{SCTeamId:4777,SCTeamName:"Jaro",IMTeamName:"FF Jaro"},
	IMTeamId_11094:{SCTeamId:12099,SCTeamName:"Platense",IMTeamName:"CA Platense"},
	IMTeamId_11150:{SCTeamId:11247,SCTeamName:"České Budějovice",IMTeamName:"SK Dynamo Ceske Budejovice"},
	IMTeamId_11292:{SCTeamId:8096,SCTeamName:"Tampa Bay Rowdies",IMTeamName:"FC Tampa Bay Rowdies"},
	IMTeamId_11448:{SCTeamId:12305,SCTeamName:"Melipilla",IMTeamName:"Deportes Melipilla"},
	IMTeamId_11457:{SCTeamId:33172,SCTeamName:"New York RB II",IMTeamName:"New York Red Bulls II"},
	IMTeamId_12187:{SCTeamId:4514,SCTeamName:"Altay",IMTeamName:"Altay"},
	IMTeamId_12223:{SCTeamId:5638,SCTeamName:"São Paulo",IMTeamName:"Sao Paulo FC"},
	IMTeamId_12224:{SCTeamId:5812,SCTeamName:"Atlético GO",IMTeamName:"Atletico Clube Goianiense"},
	IMTeamId_12633:{SCTeamId:5650,SCTeamName:"Juventude",IMTeamName:"Esporte Clube Juventude"},
	IMTeamId_12637:{SCTeamId:5673,SCTeamName:"América Mineiro",IMTeamName:"America Futebol Clube MG"},
	IMTeamId_13049:{SCTeamId:16396,SCTeamName:"Stellenbosch FC",IMTeamName:"Stellenbosch FC"},
	IMTeamId_13095:{SCTeamId:6424,SCTeamName:"Kriens",IMTeamName:"SC Kriens"},
	IMTeamId_13141:{SCTeamId:33171,SCTeamName:"Colorado Springs",IMTeamName:"Colorado Springs Switchbacks FC"},
	IMTeamId_14296:{SCTeamId:5280,SCTeamName:"Beerschot-Wilrijk",IMTeamName:"Beerschot Wilrijk"},
	IMTeamId_15673:{SCTeamId:13540,SCTeamName:"Raków Częstochowa",IMTeamName:"Rakow Czestochowa"},
	IMTeamId_15678:{SCTeamId:13545,SCTeamName:"Warta Poznań",IMTeamName:"Warta Poznan"},
	IMTeamId_15757:{SCTeamId:13551,SCTeamName:"Radomiak Radom",IMTeamName:"RKS Radomiak Radom"},
	IMTeamId_15913:{SCTeamId:32930,SCTeamName:"Louisville City",IMTeamName:"Louisville City FC"},
	IMTeamId_16281:{SCTeamId:8757,SCTeamName:"Vorwärts Steyr",IMTeamName:"SK Vorwarts Steyr"},
	IMTeamId_16604:{SCTeamId:7483,SCTeamName:"Jammerbugt",IMTeamName:"Jammerbugt FC"},
	IMTeamId_16966:{SCTeamId:7490,SCTeamName:"Hvidovre",IMTeamName:"Hvidovre IF"},
	IMTeamId_17010:{SCTeamId:8786,SCTeamName:"Hartberg",IMTeamName:"TSV Hartberg"},
	IMTeamId_17062:{SCTeamId:13528,SCTeamName:"Łódzki KS",IMTeamName:"LKS Lodz"},
	IMTeamId_17486:{SCTeamId:10174,SCTeamName:"Belarus",IMTeamName:"Belarus"},
	IMTeamId_17487:{SCTeamId:9400,SCTeamName:"Bulgaria",IMTeamName:"Bulgaria"},
	IMTeamId_17488:{SCTeamId:10001,SCTeamName:"Bosnia-Herzegovina",IMTeamName:"Bosnia-Herzegovina"},
	IMTeamId_17489:{SCTeamId:12678,SCTeamName:"Greece",IMTeamName:"Greece"},
	IMTeamId_17490:{SCTeamId:7047,SCTeamName:"Sweden",IMTeamName:"Sweden"},
	IMTeamId_17493:{SCTeamId:11233,SCTeamName:"Faroe Islands",IMTeamName:"Faroe Islands"},
	IMTeamId_17494:{SCTeamId:6697,SCTeamName:"Switzerland",IMTeamName:"Switzerland"},
	IMTeamId_17495:{SCTeamId:12496,SCTeamName:"Azerbaijan",IMTeamName:"Azerbaijan"},
	IMTeamId_17496:{SCTeamId:10962,SCTeamName:"Northern Ireland",IMTeamName:"Northern Ireland"},
	IMTeamId_17497:{SCTeamId:11049,SCTeamName:"Kazakhstan",IMTeamName:"Kazakhstan"},
	IMTeamId_17498:{SCTeamId:7712,SCTeamName:"Denmark",IMTeamName:"Denmark"},
	IMTeamId_17499:{SCTeamId:8664,SCTeamName:"Scotland",IMTeamName:"Scotland"},
	IMTeamId_17500:{SCTeamId:2413,SCTeamName:"England",IMTeamName:"England"},
	IMTeamId_17501:{SCTeamId:13497,SCTeamName:"Lithuania",IMTeamName:"Lithuania"},
	IMTeamId_17502:{SCTeamId:14496,SCTeamName:"Slovakia",IMTeamName:"Slovakia"},
	IMTeamId_17503:{SCTeamId:7336,SCTeamName:"Norway",IMTeamName:"Norway"},
	IMTeamId_17504:{SCTeamId:11555,SCTeamName:"Czech Republic",IMTeamName:"Czech Republic"},
	IMTeamId_17505:{SCTeamId:17371,SCTeamName:"Montenegro",IMTeamName:"Montenegro"},
	IMTeamId_17506:{SCTeamId:14947,SCTeamName:"Armenia",IMTeamName:"Armenia"},
	IMTeamId_17507:{SCTeamId:13869,SCTeamName:"Poland",IMTeamName:"Poland"},
	IMTeamId_17508:{SCTeamId:11944,SCTeamName:"Romania",IMTeamName:"Romania"},
	IMTeamId_17542:{SCTeamId:4849,SCTeamName:"Finland",IMTeamName:"Finland"},
	IMTeamId_17543:{SCTeamId:14622,SCTeamName:"Ukraine",IMTeamName:"Ukraine"},
	IMTeamId_17544:{SCTeamId:8274,SCTeamName:"Republic of Ireland",IMTeamName:"Republic of Ireland"},
	IMTeamId_17545:{SCTeamId:9109,SCTeamName:"Austria",IMTeamName:"Austria"},
	IMTeamId_17546:{SCTeamId:7839,SCTeamName:"Iceland",IMTeamName:"Iceland"},
	IMTeamId_17548:{SCTeamId:17322,SCTeamName:"Serbia",IMTeamName:"Serbia"},
	IMTeamId_17549:{SCTeamId:10682,SCTeamName:"Wales",IMTeamName:"Wales"},
	IMTeamId_17550:{SCTeamId:13382,SCTeamName:"Israel",IMTeamName:"Israel"},
	IMTeamId_17551:{SCTeamId:8731,SCTeamName:"Albania",IMTeamName:"Albania"},
	IMTeamId_17552:{SCTeamId:11163,SCTeamName:"Moldova",IMTeamName:"Moldova"},
	IMTeamId_17553:{SCTeamId:15874,SCTeamName:"Georgia",IMTeamName:"Georgia"},
	IMTeamId_18197:{SCTeamId:12274,SCTeamName:"Argentina",IMTeamName:"Argentina"},
	IMTeamId_18200:{SCTeamId:664,SCTeamName:"Netherlands",IMTeamName:"Netherlands"},
	IMTeamId_18201:{SCTeamId:15670,SCTeamName:"Uruguay",IMTeamName:"Uruguay"},
	IMTeamId_18203:{SCTeamId:4687,SCTeamName:"Turkey",IMTeamName:"Turkey"},
	IMTeamId_18209:{SCTeamId:15797,SCTeamName:"Ecuador",IMTeamName:"Ecuador"},
	IMTeamId_18211:{SCTeamId:15516,SCTeamName:"Paraguay",IMTeamName:"Paraguay"},
	IMTeamId_18215:{SCTeamId:15594,SCTeamName:"Peru",IMTeamName:"Peru"},
	IMTeamId_18967:{SCTeamId:9059,SCTeamName:"Austria Klagenfurt",IMTeamName:"SK Austria Klagenfurt"},
	IMTeamId_18968:{SCTeamId:9086,SCTeamName:"Lafnitz",IMTeamName:"SV Lafnitz"},
	IMTeamId_19545:{SCTeamId:13556,SCTeamName:"Odra Opole",IMTeamName:"Odra Opole"},
	IMTeamId_20250:{SCTeamId:15757,SCTeamName:"Venezuela",IMTeamName:"Venezuela"},
	IMTeamId_20251:{SCTeamId:10451,SCTeamName:"Hungary",IMTeamName:"Hungary"},
	IMTeamId_20486:{SCTeamId:10753,SCTeamName:"Cyprus",IMTeamName:"Cyprus"},
	IMTeamId_20755:{SCTeamId:15626,SCTeamName:"San Marino",IMTeamName:"San Marino"},
	IMTeamId_20889:{SCTeamId:13591,SCTeamName:"Jastrzębie",IMTeamName:"GKS Jastrzebie"},
	IMTeamId_21356:{SCTeamId:10491,SCTeamName:"Bolivia",IMTeamName:"Bolivia"},
	IMTeamId_21363:{SCTeamId:14765,SCTeamName:"Luxembourg",IMTeamName:"Luxembourg"},
	IMTeamId_21760:{SCTeamId:37891,SCTeamName:"Rio Grande Valley",IMTeamName:"Rio Grande Valley FC"},
	IMTeamId_22139:{SCTeamId:4825,SCTeamName:"JIPPO",IMTeamName:"JIPPO"},
	IMTeamId_22464:{SCTeamId:15336,SCTeamName:"Malta",IMTeamName:"Malta"},
	IMTeamId_22504:{SCTeamId:22124,SCTeamName:"Kosovo",IMTeamName:"Kosovo"},
	IMTeamId_22506:{SCTeamId:13083,SCTeamName:"Estonia",IMTeamName:"Estonia"},
	IMTeamId_22509:{SCTeamId:19827,SCTeamName:"Gibraltar",IMTeamName:"Gibraltar"},
	IMTeamId_22510:{SCTeamId:13262,SCTeamName:"Latvia",IMTeamName:"Latvia"},
	IMTeamId_22513:{SCTeamId:12046,SCTeamName:"Slovenia",IMTeamName:"Slovenia"},
	IMTeamId_22816:{SCTeamId:17711,SCTeamName:"Liechtenstein",IMTeamName:"Liechtenstein"},
	IMTeamId_22828:{SCTeamId:16460,SCTeamName:"Qatar",IMTeamName:"Qatar"},
	IMTeamId_24318:{SCTeamId:13618,SCTeamName:"Resovia Rzeszów",IMTeamName:"Resovia Rzeszow"},
	IMTeamId_25312:{SCTeamId:3162,SCTeamName:"Lazio",IMTeamName:"Lazio"},
	IMTeamId_26487:{SCTeamId:15647,SCTeamName:"Deportivo Maldonado",IMTeamName:"Deportivo Maldonado"},
	IMTeamId_27141:{SCTeamId:25866,SCTeamName:"Atlético de San Luis",IMTeamName:"Atletico San Luis"},
	IMTeamId_27308:{SCTeamId:13712,SCTeamName:"Nieciecza",IMTeamName:"Bruk-Bet Termalica Nieciecza"},
	IMTeamId_29189:{SCTeamId:31278,SCTeamName:"Mura",IMTeamName:"NS Mura"},
	IMTeamId_29350:{SCTeamId:3867,SCTeamName:"Rodez",IMTeamName:"Rodez AF"},
	IMTeamId_29616:{SCTeamId:364,SCTeamName:"AZ II",IMTeamName:"Jong AZ Alkmaar"},
	IMTeamId_30203:{SCTeamId:1763,SCTeamName:"Weymouth",IMTeamName:"Weymouth"},
	IMTeamId_30245:{SCTeamId:5088,SCTeamName:"Antwerp",IMTeamName:"Royal Antwerp"},
	IMTeamId_31101:{SCTeamId:12312,SCTeamName:"Curicó Unido",IMTeamName:"Curico Unido"},
	IMTeamId_31174:{SCTeamId:15440,SCTeamName:"Correcaminos UAT",IMTeamName:"Correcaminos de la UAT"},
	IMTeamId_32212:{SCTeamId:9657,SCTeamName:"Farense",IMTeamName:"SC Farense"},
	IMTeamId_32342:{SCTeamId:15428,SCTeamName:"Venados",IMTeamName:"Venados FC"},
	IMTeamId_32524:{SCTeamId:9670,SCTeamName:"Vilafranquense",IMTeamName:"UDV Vilafranquense"},
	IMTeamId_32604:{SCTeamId:15458,SCTeamName:"Tampico Madero",IMTeamName:"Tampico Madero FC"},
	IMTeamId_33258:{SCTeamId:4197,SCTeamName:"Cholet",IMTeamName:"SO Cholet"},
	IMTeamId_34650:{SCTeamId:3798,SCTeamName:"Grenoble",IMTeamName:"Grenoble Foot 38"},
	IMTeamId_39847:{SCTeamId:4059,SCTeamName:"Villefranche",IMTeamName:"FC Villefranche"},
	IMTeamId_39849:{SCTeamId:60178,SCTeamName:"Bastia-Borgo",IMTeamName:"Bastia Borgo"},
	IMTeamId_40250:{SCTeamId:9708,SCTeamName:"Casa Pia",IMTeamName:"Casa Pia AC"},
	IMTeamId_44762:{SCTeamId:3236,SCTeamName:"Monza",IMTeamName:"Monza"},
	IMTeamId_46044:{SCTeamId:6422,SCTeamName:"Yverdon Sport",IMTeamName:"Yverdon Sport"},
	IMTeamId_46459:{SCTeamId:6526,SCTeamName:"Stade Lausanne-Ouchy",IMTeamName:"FC Stade Lausanne Ouchy"},
	IMTeamId_47297:{SCTeamId:5132,SCTeamName:"RFC Seraing",IMTeamName:"RFC Seraing"},
	IMTeamId_48759:{SCTeamId:4539,SCTeamName:"Fatih Karagümrük",IMTeamName:"Fatih Karagumruk"},
	IMTeamId_50540:{SCTeamId:2412,SCTeamName:"King's Lynn Town",IMTeamName:"Kings Lynn FC"},
	IMTeamId_51550:{SCTeamId:9685,SCTeamName:"Trofense",IMTeamName:"CD Trofense"},
	IMTeamId_53078:{SCTeamId:4427,SCTeamName:"Annecy",IMTeamName:"FC Annecy"},
	IMTeamId_54586:{SCTeamId:3810,SCTeamName:"Sète",IMTeamName:"FC Sete 34"},
	IMTeamId_54692:{SCTeamId:9649,SCTeamName:"Mafra",IMTeamName:"CD Mafra"},
	IMTeamId_56756:{SCTeamId:3786,SCTeamName:"Le Mans",IMTeamName:"Le Mans"},
	IMTeamId_59069:{SCTeamId:3827,SCTeamName:"Stade Briochin",IMTeamName:"Stade Briochin"},
	IMTeamId_60316:{SCTeamId:60341,SCTeamName:"Ibiza",IMTeamName:"UD Ibiza"},
	IMTeamId_60951:{SCTeamId:30149,SCTeamName:"Nashville SC",IMTeamName:"Nashville SC"},
	IMTeamId_62054:{SCTeamId:62148,SCTeamName:"Los Angeles FC",IMTeamName:"Los Angeles FC"},
	IMTeamId_72781:{SCTeamId:13517,SCTeamName:"Górnik Polkowice",IMTeamName:"KS Polkowice"},
	IMTeamId_76445:{SCTeamId:9905,SCTeamName:"Portugal",IMTeamName:"Portugal"},
	IMTeamId_76510:{SCTeamId:14358,SCTeamName:"Russia",IMTeamName:"Russia"},
	IMTeamId_76738:{SCTeamId:9598,SCTeamName:"Croatia",IMTeamName:"Croatia"},
	IMTeamId_76743:{SCTeamId:6380,SCTeamName:"Brazil",IMTeamName:"Brazil"},
	IMTeamId_76851:{SCTeamId:5629,SCTeamName:"Belgium",IMTeamName:"Belgium"},
	IMTeamId_76948:{SCTeamId:19812,SCTeamName:"Lincoln Red Imps",IMTeamName:"Lincoln Red Imps"},
	IMTeamId_77832:{SCTeamId:7499,SCTeamName:"SønderjyskE",IMTeamName:"Sonderjyske"},
	IMTeamId_77877:{SCTeamId:8951,SCTeamName:"FC Juniors OÖ",IMTeamName:"FC Juniors OO"},
	IMTeamId_78281:{SCTeamId:6425,SCTeamName:"Luzern",IMTeamName:"FC Luzern"},
	IMTeamId_78379:{SCTeamId:6412,SCTeamName:"Zürich",IMTeamName:"FC Zurich"},
	IMTeamId_78380:{SCTeamId:2448,SCTeamName:"Bochum",IMTeamName:"VfL Bochum"},
	IMTeamId_78915:{SCTeamId:2579,SCTeamName:"Ingolstadt",IMTeamName:"FC Ingolstadt 04"},
	IMTeamId_79059:{SCTeamId:12190,SCTeamName:"Central Córdoba SdE",IMTeamName:"Central Cordoba De Santiago Del Estero"},
	IMTeamId_79450:{SCTeamId:8735,SCTeamName:"Grazer AK",IMTeamName:"Grazer AK"},
	IMTeamId_79772:{SCTeamId:3159,SCTeamName:"Juventus",IMTeamName:"Juventus"},
	IMTeamId_79776:{SCTeamId:1611,SCTeamName:"Manchester United",IMTeamName:"Manchester United"},
	IMTeamId_80090:{SCTeamId:8772,SCTeamName:"Austria Wien II",IMTeamName:"Young Violets Austria Vienna"},
	IMTeamId_80199:{SCTeamId:1631,SCTeamName:"Leicester City",IMTeamName:"Leicester City"},
	IMTeamId_80672:{SCTeamId:1609,SCTeamName:"Arsenal",IMTeamName:"Arsenal"},
	IMTeamId_80673:{SCTeamId:9607,SCTeamName:"Benfica",IMTeamName:"Benfica"},
	IMTeamId_80987:{SCTeamId:676,SCTeamName:"Barcelona",IMTeamName:"Barcelona"},
	IMTeamId_81869:{SCTeamId:1628,SCTeamName:"Crystal Palace",IMTeamName:"Crystal Palace"},
	IMTeamId_81955:{SCTeamId:8748,SCTeamName:"Kapfenberger SV",IMTeamName:"Kapfenberger SV"},
	IMTeamId_83605:{SCTeamId:4235,SCTeamName:"Chambly",IMTeamName:"FC Chambly"},
	IMTeamId_83661:{SCTeamId:1679,SCTeamName:"Mansfield Town",IMTeamName:"Mansfield Town"},
	IMTeamId_83772:{SCTeamId:4829,SCTeamName:"Ekenäs IF",IMTeamName:"Ekenas Idrottsforening"},
	IMTeamId_84625:{SCTeamId:12430,SCTeamName:"Colombia",IMTeamName:"Colombia"},
	IMTeamId_84786:{SCTeamId:12820,SCTeamName:"Vegalta Sendai",IMTeamName:"Vegalta Sendai"},
	IMTeamId_84966:{SCTeamId:14995,SCTeamName:"Toronto",IMTeamName:"Toronto FC"},
	IMTeamId_85118:{SCTeamId:697,SCTeamName:"Sporting Gijón",IMTeamName:"Sporting Gijon"},
	IMTeamId_85611:{SCTeamId:1882,SCTeamName:"Fleetwood Town",IMTeamName:"Fleetwood Town FC"},
	IMTeamId_85618:{SCTeamId:3785,SCTeamName:"Guingamp",IMTeamName:"EA Guingamp"},
	IMTeamId_85639:{SCTeamId:12825,SCTeamName:"Tokushima Vortis",IMTeamName:"Tokushima Vortis"},
	IMTeamId_85645:{SCTeamId:8155,SCTeamName:"St. Patrick's Ath.",IMTeamName:"St. Patricks Athletic FC"},
	IMTeamId_86160:{SCTeamId:6754,SCTeamName:"Mjällby",IMTeamName:"Mjallby AIF"},
	IMTeamId_86187:{SCTeamId:4542,SCTeamName:"Gaziantep",IMTeamName:"Gazisehir Gaziantep"},
	IMTeamId_86194:{SCTeamId:6766,SCTeamName:"Sirius",IMTeamName:"IK Sirius FK"},
	IMTeamId_86267:{SCTeamId:36,SCTeamName:"TOP Oss",IMTeamName:"Top Oss"},
	IMTeamId_86381:{SCTeamId:12210,SCTeamName:"Patronato",IMTeamName:"CA Patronato"},
	IMTeamId_86388:{SCTeamId:3779,SCTeamName:"Strasbourg",IMTeamName:"RC Strasbourg"},
	IMTeamId_90119:{SCTeamId:12057,SCTeamName:"Boca Juniors",IMTeamName:"Boca Juniors"},
	IMTeamId_90152:{SCTeamId:12085,SCTeamName:"Huracán",IMTeamName:"Club Atletico Huracan"},
	IMTeamId_90153:{SCTeamId:12073,SCTeamName:"Vélez Sarsfield",IMTeamName:"CA Velez Sarsfield"},
	IMTeamId_90581:{SCTeamId:12800,SCTeamName:"Kashima Antlers",IMTeamName:"Kashima Antlers"},
	IMTeamId_91315:{SCTeamId:12069,SCTeamName:"River Plate",IMTeamName:"CA River Plate"},
	IMTeamId_92907:{SCTeamId:3311,SCTeamName:"Cosenza",IMTeamName:"Cosenza"},
	IMTeamId_95866:{SCTeamId:5663,SCTeamName:"Fortaleza",IMTeamName:"Fortaleza Esporte Clube"},
	IMTeamId_95940:{SCTeamId:1659,SCTeamName:"Bournemouth",IMTeamName:"AFC Bournemouth"},
	IMTeamId_96038:{SCTeamId:63663,SCTeamName:"TS Galaxy FC",IMTeamName:"TS Galaxy"},
	IMTeamId_96109:{SCTeamId:8,SCTeamName:"ADO Den Haag",IMTeamName:"ADO Den Haag"},
	IMTeamId_96164:{SCTeamId:7465,SCTeamName:"Horsens",IMTeamName:"AC Horsens"},
	IMTeamId_96249:{SCTeamId:6421,SCTeamName:"Sion",IMTeamName:"FC Sion"},
	IMTeamId_96754:{SCTeamId:12799,SCTeamName:"Urawa Reds",IMTeamName:"Urawa Red Diamonds"},
	IMTeamId_96992:{SCTeamId:18,SCTeamName:"NAC Breda",IMTeamName:"NAC Breda"},
	IMTeamId_98045:{SCTeamId:10073,SCTeamName:"North Macedonia",IMTeamName:"Republic of North Macedonia"},
	IMTeamId_98056:{SCTeamId:4535,SCTeamName:"İstanbul Başakşehir",IMTeamName:"Istanbul Basaksehir"},
	IMTeamId_98181:{SCTeamId:8742,SCTeamName:"Sturm Graz",IMTeamName:"SK Sturm Graz"},
	IMTeamId_99336:{SCTeamId:7471,SCTeamName:"Fremad Amager",IMTeamName:"Fremad Amager"},
	IMTeamId_100041:{SCTeamId:63761,SCTeamName:"Austin Bold",IMTeamName:"Austin Bold FC"},
	IMTeamId_100631:{SCTeamId:63730,SCTeamName:"Hartford Athletic",IMTeamName:"Hartford Athletic"},
	IMTeamId_100690:{SCTeamId:63760,SCTeamName:"Memphis 901",IMTeamName:"Memphis 901 FC"},
	IMTeamId_101065:{SCTeamId:1917,SCTeamName:"Boreham Wood",IMTeamName:"Boreham Wood FC"},
	IMTeamId_101137:{SCTeamId:9702,SCTeamName:"Famalicão",IMTeamName:"FC Famalicao"},
	IMTeamId_101159:{SCTeamId:8518,SCTeamName:"Aberdeen",IMTeamName:"Aberdeen FC"},
	IMTeamId_101334:{SCTeamId:3315,SCTeamName:"Sassuolo",IMTeamName:"US Sassuolo"},
	IMTeamId_103493:{SCTeamId:3172,SCTeamName:"Atalanta",IMTeamName:"Atalanta"},
	IMTeamId_103494:{SCTeamId:7453,SCTeamName:"Brøndby",IMTeamName:"Brondby IF"},
	IMTeamId_103495:{SCTeamId:9608,SCTeamName:"Sporting CP",IMTeamName:"Sporting Lisbon"},
	IMTeamId_103714:{SCTeamId:1624,SCTeamName:"Tottenham Hotspur",IMTeamName:"Tottenham Hotspur"},
	IMTeamId_104330:{SCTeamId:15405,SCTeamName:"América",IMTeamName:"Club America"},
	IMTeamId_104871:{SCTeamId:8801,SCTeamName:"Rapid Wien II",IMTeamName:"SK Rapid Wien II"},
	IMTeamId_106607:{SCTeamId:3191,SCTeamName:"Venezia",IMTeamName:"Venezia"},
	IMTeamId_107298:{SCTeamId:12293,SCTeamName:"Everton",IMTeamName:"Everton Vina del Mar"},
	IMTeamId_109237:{SCTeamId:5091,SCTeamName:"Zulte-Waregem",IMTeamName:"Zulte Waregem"},
	IMTeamId_109422:{SCTeamId:5082,SCTeamName:"Sint-Truiden",IMTeamName:"Sint-Truidense VV"},
	IMTeamId_109447:{SCTeamId:13504,SCTeamName:"Wisła Kraków",IMTeamName:"Wisla Krakow"},
	IMTeamId_109485:{SCTeamId:23568,SCTeamName:"Utrecht U21/U23",IMTeamName:"Jong FC Utrecht"},
	IMTeamId_109486:{SCTeamId:13713,SCTeamName:"Puszcza Niepołomice",IMTeamName:"MKS Puszcza Niepolomice"},
	IMTeamId_109490:{SCTeamId:11259,SCTeamName:"Bohemians 1905",IMTeamName:"Bohemians 1905"},
	IMTeamId_109653:{SCTeamId:11255,SCTeamName:"Viktoria Plzeň",IMTeamName:"FC Viktoria Plzen"},
	IMTeamId_109655:{SCTeamId:1695,SCTeamName:"Scunthorpe United",IMTeamName:"Scunthorpe United"},
	IMTeamId_109657:{SCTeamId:10530,SCTeamName:"Wrexham",IMTeamName:"Wrexham"},
	IMTeamId_109659:{SCTeamId:8745,SCTeamName:"Wacker Innsbruck",IMTeamName:"FC Wacker Innsbruck"},
	IMTeamId_109708:{SCTeamId:8743,SCTeamName:"Salzburg",IMTeamName:"Red Bull Salzburg"},
	IMTeamId_109710:{SCTeamId:8526,SCTeamName:"St. Mirren",IMTeamName:"Saint Mirren"},
	IMTeamId_109711:{SCTeamId:1668,SCTeamName:"Peterborough United",IMTeamName:"Peterborough United"},
	IMTeamId_110149:{SCTeamId:14,SCTeamName:"Roda JC",IMTeamName:"Roda JC"},
	IMTeamId_110223:{SCTeamId:2450,SCTeamName:"Hamburger SV",IMTeamName:"Hamburger SV"},
	IMTeamId_110279:{SCTeamId:13508,SCTeamName:"Wisła Płock",IMTeamName:"Wisla Plock"},
	IMTeamId_110393:{SCTeamId:1640,SCTeamName:"Coventry City",IMTeamName:"Coventry City"},
	IMTeamId_110867:{SCTeamId:42,SCTeamName:"Eindhoven",IMTeamName:"FC Eindhoven"},
	IMTeamId_110973:{SCTeamId:9707,SCTeamName:"Benfica II",IMTeamName:"Benfica B"},
	IMTeamId_111625:{SCTeamId:3770,SCTeamName:"Nantes",IMTeamName:"FC Nantes"},
	IMTeamId_111692:{SCTeamId:695,SCTeamName:"Levante",IMTeamName:"Levante UD"},
	IMTeamId_111811:{SCTeamId:4488,SCTeamName:"Trabzonspor",IMTeamName:"Trabzonspor"},
	IMTeamId_111921:{SCTeamId:789,SCTeamName:"Real Oviedo",IMTeamName:"Real Oviedo"},
	IMTeamId_111940:{SCTeamId:698,SCTeamName:"Getafe",IMTeamName:"Getafe CF"},
	IMTeamId_112376:{SCTeamId:686,SCTeamName:"Mallorca",IMTeamName:"RCD Mallorca"},
	IMTeamId_113506:{SCTeamId:16340,SCTeamName:"Moroka Swallows",IMTeamName:"Moroka Swallows FC"},
	IMTeamId_114961:{SCTeamId:14913,SCTeamName:"Andorra",IMTeamName:"Andorra"},
	IMTeamId_123986:{SCTeamId:5685,SCTeamName:"Red Bull Bragantino",IMTeamName:"Red Bull Bragantino SP"},
	IMTeamId_125500:{SCTeamId:66193,SCTeamName:"Inter Miami",IMTeamName:"Inter Miami CF"},
	IMTeamId_137984:{SCTeamId:7852,SCTeamName:"DC United",IMTeamName:"Washington D.C. United"},
	IMTeamId_138867:{SCTeamId:66847,SCTeamName:"Mazatlán",IMTeamName:"Mazatlan FC"},
	IMTeamId_141292:{SCTeamId:66958,SCTeamName:"Pumas Tabasco",IMTeamName:"Pumas Tabasco"},
	IMTeamId_141408:{SCTeamId:66957,SCTeamName:"Cancún",IMTeamName:"Cancun FC"},
	IMTeamId_142238:{SCTeamId:66959,SCTeamName:"Tapatío",IMTeamName:"CD Tapatio"},
	IMTeamId_144862:{SCTeamId:67089,SCTeamName:"Estrela",IMTeamName:"CF Estrela da Amadora"},
	IMTeamId_156680:{SCTeamId:35479,SCTeamName:"Tepatitlán de Morelos",IMTeamName:"Tepatitlan FC"},
	IMTeamId_158522:{SCTeamId:67860,SCTeamName:"Austin FC",IMTeamName:"Austin FC"},
	IMTeamId_158579:{SCTeamId:8142,SCTeamName:"CF Montréal",IMTeamName:"CF Montreal"},
	IMTeamId_159006:{SCTeamId:9143,SCTeamName:"Henan Songshan Longmen",IMTeamName:"Henan Songshan Longmen"},
	IMTeamId_159007:{SCTeamId:9133,SCTeamName:"Chongqing Liangjiang",IMTeamName:"Chongqing Liangjiang Athletic"},
	IMTeamId_159008:{SCTeamId:9135,SCTeamName:"Shandong Taishan",IMTeamName:"Shandong Taishan"},
	IMTeamId_159013:{SCTeamId:9174,SCTeamName:"Guangzhou FC",IMTeamName:"Guangzhou FC"},
	IMTeamId_159014:{SCTeamId:9126,SCTeamName:"Guangzhou City",IMTeamName:"Guangzhou City FC"},
	IMTeamId_159016:{SCTeamId:28726,SCTeamName:"Qingdao FC",IMTeamName:"Qingdao FC"},
	IMTeamId_159017:{SCTeamId:21877,SCTeamName:"Cangzhou Mighty Lions",IMTeamName:"Cangzhou Mighty Lions FC"},
	IMTeamId_159020:{SCTeamId:9132,SCTeamName:"Tianjin Tigers",IMTeamName:"Tianjin Jinmen Tiger(N)"},
	IMTeamId_159021:{SCTeamId:9182,SCTeamName:"Shanghai Port",IMTeamName:"Shanghai Port FC"},
	IMTeamId_159092:{SCTeamId:22275,SCTeamName:"Hebei",IMTeamName:"Hebei FC"},
	IMTeamId_159093:{SCTeamId:9189,SCTeamName:"Wuhan FC",IMTeamName:"Wuhan FC"},
	IMTeamId_159123:{SCTeamId:9134,SCTeamName:"Shanghai Shenhua",IMTeamName:"Shanghai Shenhua FC"},
	IMTeamId_159124:{SCTeamId:9130,SCTeamName:"Beijing Guoan",IMTeamName:"Beijing Guoan FC"},
	IMTeamId_171698:{SCTeamId:68502,SCTeamName:"Raya2",IMTeamName:"Raya2 Expansion"},
	IMTeamId_174762:{SCTeamId:16403,SCTeamName:"Marumo Gallants",IMTeamName:"Marumo Gallants FC"},
}
