export const TeamsData = [{
  "id": 1,
  "englishName": "Argentina",
  "localizedName": "阿根廷",
  "imgSrc": require("../../../images/worldCup/flags/ARG.jpg")
},
  {
    "id": 2,
    "englishName": "Australia",
    "localizedName": "澳大利亚",
    "imgSrc": require("../../../images/worldCup/flags/AUS.jpg")
  }, {
    "id": 3,
    "englishName": "Belgium",
    "localizedName": "比利时",
    "imgSrc": require("../../../images/worldCup/flags/BEL.jpg")
  }, {
    "id": 4,
    "englishName": "Brazil",
    "localizedName": "巴西",
    "imgSrc": require("../../../images/worldCup/flags/BRA.jpg")
  }, {
    "id": 5,
    "englishName": "Cameroon",
    "localizedName": "喀麦隆"
  }, {
    "id": 6,
    "englishName": "Canada",
    "localizedName": "加拿大",
    "imgSrc": require("../../../images/worldCup/flags/CAN.jpg")
  }, {
    "id": 7,
    "englishName": "Costa Rica",
    "localizedName": "哥斯达黎加",
    "imgSrc": require("../../../images/worldCup/flags/CRC.jpg")
  }, {
    "id": 8,
    "englishName": "Croatia",
    "localizedName": "克罗地亚",
    "imgSrc": require("../../../images/worldCup/flags/CRO.jpg")
  }, {
    "id": 9,
    "englishName": "Denmark",
    "localizedName": "丹麦",
    "imgSrc": require("../../../images/worldCup/flags/DEN.jpg")
  }, {
    "id": 10,
    "englishName": "Ecuador",
    "localizedName": "厄瓜多尔",
    "imgSrc": require("../../../images/worldCup/flags/Ecuador.jpg")
  }, {
    "id": 11,
    "englishName": "England",
    "localizedName": "英格兰",
    "imgSrc": require("../../../images/worldCup/flags/ENG.jpg")
  }, {
    "id": 12,
    "englishName": "France",
    "localizedName": "法国",
    "imgSrc": require("../../../images/worldCup/flags/FRA.jpg")
  }, {
    "id": 13,
    "englishName": "Germany",
    "localizedName": "德国",
    "imgSrc": require("../../../images/worldCup/flags/GER.jpg")
  }, {
    "id": 14,
    "englishName": "Ghana",
    "localizedName": "加纳",
    "imgSrc": require("../../../images/worldCup/flags/GHA.jpg")
  }, {
    "id": 15,
    "englishName": "Iran",
    "localizedName": "伊朗",
    "imgSrc": require("../../../images/worldCup/flags/IRN.jpg")
  }, {
    "id": 16,
    "englishName": "Japan",
    "localizedName": "日本",
    "imgSrc": require("../../../images/worldCup/flags/JPN.jpg")
  }, {
    "id": 17,
    "englishName": "Mexico",
    "localizedName": "墨西哥",
    "imgSrc": require("../../../images/worldCup/flags/MEX.jpg")
  }, {
    "id": 18,
    "englishName": "Morocco",
    "localizedName": "摩洛哥",
    "imgSrc": require("../../../images/worldCup/flags/MAR.jpg")
  },
  {
    "id": 19,
    "englishName": "Netherlands",
    "localizedName": "荷兰",
    "imgSrc": require("../../../images/worldCup/flags/Netherlands.jpg")
  }, {
    "id": 20,
    "englishName": "Poland",
    "localizedName": "波兰",
    "imgSrc": require("../../../images/worldCup/flags/POL.jpg")
  }, {
    "id": 21,
    "englishName": "Portugal",
    "localizedName": "葡萄牙",
    "imgSrc": require("../../../images/worldCup/flags/POR.jpg")
  }, {
    "id": 22,
    "englishName": "Qatar",
    "localizedName": "卡达尔",
    "imgSrc": require("../../../images/worldCup/flags/Qatar.jpg")
  }, {
    "id": 23,
    "englishName": "Saudi Arabia",
    "localizedName": "沙地阿拉伯",
    "imgSrc": require("../../../images/worldCup/flags/KSA.jpg")
  }, {
    "id": 24,
    "englishName": "Senegal",
    "localizedName": "塞内加尔",
    "imgSrc": require("../../../images/worldCup/flags/Senegal.jpg")
  }, {
    "id": 25,
    "englishName": "Serbia",
    "localizedName": "塞尔维亚"
  }, {
    "id": 26,
    "englishName": "South Korea",
    "localizedName": "韩国",
    "imgSrc": require("../../../images/worldCup/flags/KOR.jpg")
  }, {
    "id": 27,
    "englishName": "Spain",
    "localizedName": "西班牙",
    "imgSrc": require("../../../images/worldCup/flags/ESP.jpg")
  }, {
    "id": 28,
    "englishName": "Switzerland",
    "localizedName": "瑞士",
    "imgSrc": require("../../../images/worldCup/flags/SUI.jpg")
  }, {
    "id": 29,
    "englishName": "Tunisia",
    "localizedName": "突尼斯",
    "imgSrc": require("../../../images/worldCup/flags/TUN.jpg")
  }, {
    "id": 30,
    "englishName": "United States",
    "localizedName": "美国",
    "imgSrc": require("../../../images/worldCup/flags/USA.jpg")
  }, {
    "id": 31,
    "englishName": "Uruguay",
    "localizedName": "乌拉圭",
    "imgSrc": require("../../../images/worldCup/flags/URU.jpg")
  }, {
    "id": 32,
    "englishName": "Wales",
    "localizedName": "威尔士",
    "imgSrc": require("../../../images/worldCup/flags/WAL.jpg")
  }
]
